# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/estudio/CLionProjects/clava/ClangAstDumper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/estudio/CLionProjects/clava

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/estudio/CLionProjects/clava/CMakeFiles /home/estudio/CLionProjects/clava/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/estudio/CLionProjects/clava/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ClangAstDumper

# Build rule for target.
ClangAstDumper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAstDumper
.PHONY : ClangAstDumper

# fast build rule for target.
ClangAstDumper/fast:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/build
.PHONY : ClangAstDumper/fast

ChildrenVisitorAttrs.o: ChildrenVisitorAttrs.cpp.o

.PHONY : ChildrenVisitorAttrs.o

# target to build an object file
ChildrenVisitorAttrs.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorAttrs.cpp.o
.PHONY : ChildrenVisitorAttrs.cpp.o

ChildrenVisitorAttrs.i: ChildrenVisitorAttrs.cpp.i

.PHONY : ChildrenVisitorAttrs.i

# target to preprocess a source file
ChildrenVisitorAttrs.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorAttrs.cpp.i
.PHONY : ChildrenVisitorAttrs.cpp.i

ChildrenVisitorAttrs.s: ChildrenVisitorAttrs.cpp.s

.PHONY : ChildrenVisitorAttrs.s

# target to generate assembly for a file
ChildrenVisitorAttrs.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorAttrs.cpp.s
.PHONY : ChildrenVisitorAttrs.cpp.s

ChildrenVisitorDecls.o: ChildrenVisitorDecls.cpp.o

.PHONY : ChildrenVisitorDecls.o

# target to build an object file
ChildrenVisitorDecls.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorDecls.cpp.o
.PHONY : ChildrenVisitorDecls.cpp.o

ChildrenVisitorDecls.i: ChildrenVisitorDecls.cpp.i

.PHONY : ChildrenVisitorDecls.i

# target to preprocess a source file
ChildrenVisitorDecls.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorDecls.cpp.i
.PHONY : ChildrenVisitorDecls.cpp.i

ChildrenVisitorDecls.s: ChildrenVisitorDecls.cpp.s

.PHONY : ChildrenVisitorDecls.s

# target to generate assembly for a file
ChildrenVisitorDecls.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorDecls.cpp.s
.PHONY : ChildrenVisitorDecls.cpp.s

ChildrenVisitorExtras.o: ChildrenVisitorExtras.cpp.o

.PHONY : ChildrenVisitorExtras.o

# target to build an object file
ChildrenVisitorExtras.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorExtras.cpp.o
.PHONY : ChildrenVisitorExtras.cpp.o

ChildrenVisitorExtras.i: ChildrenVisitorExtras.cpp.i

.PHONY : ChildrenVisitorExtras.i

# target to preprocess a source file
ChildrenVisitorExtras.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorExtras.cpp.i
.PHONY : ChildrenVisitorExtras.cpp.i

ChildrenVisitorExtras.s: ChildrenVisitorExtras.cpp.s

.PHONY : ChildrenVisitorExtras.s

# target to generate assembly for a file
ChildrenVisitorExtras.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorExtras.cpp.s
.PHONY : ChildrenVisitorExtras.cpp.s

ChildrenVisitorStmts.o: ChildrenVisitorStmts.cpp.o

.PHONY : ChildrenVisitorStmts.o

# target to build an object file
ChildrenVisitorStmts.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorStmts.cpp.o
.PHONY : ChildrenVisitorStmts.cpp.o

ChildrenVisitorStmts.i: ChildrenVisitorStmts.cpp.i

.PHONY : ChildrenVisitorStmts.i

# target to preprocess a source file
ChildrenVisitorStmts.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorStmts.cpp.i
.PHONY : ChildrenVisitorStmts.cpp.i

ChildrenVisitorStmts.s: ChildrenVisitorStmts.cpp.s

.PHONY : ChildrenVisitorStmts.s

# target to generate assembly for a file
ChildrenVisitorStmts.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorStmts.cpp.s
.PHONY : ChildrenVisitorStmts.cpp.s

ChildrenVisitorTypes.o: ChildrenVisitorTypes.cpp.o

.PHONY : ChildrenVisitorTypes.o

# target to build an object file
ChildrenVisitorTypes.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorTypes.cpp.o
.PHONY : ChildrenVisitorTypes.cpp.o

ChildrenVisitorTypes.i: ChildrenVisitorTypes.cpp.i

.PHONY : ChildrenVisitorTypes.i

# target to preprocess a source file
ChildrenVisitorTypes.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorTypes.cpp.i
.PHONY : ChildrenVisitorTypes.cpp.i

ChildrenVisitorTypes.s: ChildrenVisitorTypes.cpp.s

.PHONY : ChildrenVisitorTypes.s

# target to generate assembly for a file
ChildrenVisitorTypes.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ChildrenVisitorTypes.cpp.s
.PHONY : ChildrenVisitorTypes.cpp.s

ClangAst.o: ClangAst.cpp.o

.PHONY : ClangAst.o

# target to build an object file
ClangAst.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAst.cpp.o
.PHONY : ClangAst.cpp.o

ClangAst.i: ClangAst.cpp.i

.PHONY : ClangAst.i

# target to preprocess a source file
ClangAst.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAst.cpp.i
.PHONY : ClangAst.cpp.i

ClangAst.s: ClangAst.cpp.s

.PHONY : ClangAst.s

# target to generate assembly for a file
ClangAst.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAst.cpp.s
.PHONY : ClangAst.cpp.s

ClangAstDumper.o: ClangAstDumper.cpp.o

.PHONY : ClangAstDumper.o

# target to build an object file
ClangAstDumper.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumper.cpp.o
.PHONY : ClangAstDumper.cpp.o

ClangAstDumper.i: ClangAstDumper.cpp.i

.PHONY : ClangAstDumper.i

# target to preprocess a source file
ClangAstDumper.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumper.cpp.i
.PHONY : ClangAstDumper.cpp.i

ClangAstDumper.s: ClangAstDumper.cpp.s

.PHONY : ClangAstDumper.s

# target to generate assembly for a file
ClangAstDumper.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumper.cpp.s
.PHONY : ClangAstDumper.cpp.s

ClangAstDumperDecls.o: ClangAstDumperDecls.cpp.o

.PHONY : ClangAstDumperDecls.o

# target to build an object file
ClangAstDumperDecls.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperDecls.cpp.o
.PHONY : ClangAstDumperDecls.cpp.o

ClangAstDumperDecls.i: ClangAstDumperDecls.cpp.i

.PHONY : ClangAstDumperDecls.i

# target to preprocess a source file
ClangAstDumperDecls.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperDecls.cpp.i
.PHONY : ClangAstDumperDecls.cpp.i

ClangAstDumperDecls.s: ClangAstDumperDecls.cpp.s

.PHONY : ClangAstDumperDecls.s

# target to generate assembly for a file
ClangAstDumperDecls.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperDecls.cpp.s
.PHONY : ClangAstDumperDecls.cpp.s

ClangAstDumperExprs.o: ClangAstDumperExprs.cpp.o

.PHONY : ClangAstDumperExprs.o

# target to build an object file
ClangAstDumperExprs.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperExprs.cpp.o
.PHONY : ClangAstDumperExprs.cpp.o

ClangAstDumperExprs.i: ClangAstDumperExprs.cpp.i

.PHONY : ClangAstDumperExprs.i

# target to preprocess a source file
ClangAstDumperExprs.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperExprs.cpp.i
.PHONY : ClangAstDumperExprs.cpp.i

ClangAstDumperExprs.s: ClangAstDumperExprs.cpp.s

.PHONY : ClangAstDumperExprs.s

# target to generate assembly for a file
ClangAstDumperExprs.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperExprs.cpp.s
.PHONY : ClangAstDumperExprs.cpp.s

ClangAstDumperExtra.o: ClangAstDumperExtra.cpp.o

.PHONY : ClangAstDumperExtra.o

# target to build an object file
ClangAstDumperExtra.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperExtra.cpp.o
.PHONY : ClangAstDumperExtra.cpp.o

ClangAstDumperExtra.i: ClangAstDumperExtra.cpp.i

.PHONY : ClangAstDumperExtra.i

# target to preprocess a source file
ClangAstDumperExtra.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperExtra.cpp.i
.PHONY : ClangAstDumperExtra.cpp.i

ClangAstDumperExtra.s: ClangAstDumperExtra.cpp.s

.PHONY : ClangAstDumperExtra.s

# target to generate assembly for a file
ClangAstDumperExtra.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperExtra.cpp.s
.PHONY : ClangAstDumperExtra.cpp.s

ClangAstDumperStmts.o: ClangAstDumperStmts.cpp.o

.PHONY : ClangAstDumperStmts.o

# target to build an object file
ClangAstDumperStmts.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperStmts.cpp.o
.PHONY : ClangAstDumperStmts.cpp.o

ClangAstDumperStmts.i: ClangAstDumperStmts.cpp.i

.PHONY : ClangAstDumperStmts.i

# target to preprocess a source file
ClangAstDumperStmts.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperStmts.cpp.i
.PHONY : ClangAstDumperStmts.cpp.i

ClangAstDumperStmts.s: ClangAstDumperStmts.cpp.s

.PHONY : ClangAstDumperStmts.s

# target to generate assembly for a file
ClangAstDumperStmts.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperStmts.cpp.s
.PHONY : ClangAstDumperStmts.cpp.s

ClangAstDumperTypes.o: ClangAstDumperTypes.cpp.o

.PHONY : ClangAstDumperTypes.o

# target to build an object file
ClangAstDumperTypes.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperTypes.cpp.o
.PHONY : ClangAstDumperTypes.cpp.o

ClangAstDumperTypes.i: ClangAstDumperTypes.cpp.i

.PHONY : ClangAstDumperTypes.i

# target to preprocess a source file
ClangAstDumperTypes.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperTypes.cpp.i
.PHONY : ClangAstDumperTypes.cpp.i

ClangAstDumperTypes.s: ClangAstDumperTypes.cpp.s

.PHONY : ClangAstDumperTypes.s

# target to generate assembly for a file
ClangAstDumperTypes.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangAstDumperTypes.cpp.s
.PHONY : ClangAstDumperTypes.cpp.s

ClangEnums.o: ClangEnums.cpp.o

.PHONY : ClangEnums.o

# target to build an object file
ClangEnums.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangEnums.cpp.o
.PHONY : ClangEnums.cpp.o

ClangEnums.i: ClangEnums.cpp.i

.PHONY : ClangEnums.i

# target to preprocess a source file
ClangEnums.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangEnums.cpp.i
.PHONY : ClangEnums.cpp.i

ClangEnums.s: ClangEnums.cpp.s

.PHONY : ClangEnums.s

# target to generate assembly for a file
ClangEnums.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangEnums.cpp.s
.PHONY : ClangEnums.cpp.s

ClangNodes.o: ClangNodes.cpp.o

.PHONY : ClangNodes.o

# target to build an object file
ClangNodes.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangNodes.cpp.o
.PHONY : ClangNodes.cpp.o

ClangNodes.i: ClangNodes.cpp.i

.PHONY : ClangNodes.i

# target to preprocess a source file
ClangNodes.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangNodes.cpp.i
.PHONY : ClangNodes.cpp.i

ClangNodes.s: ClangNodes.cpp.s

.PHONY : ClangNodes.s

# target to generate assembly for a file
ClangNodes.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangNodes.cpp.s
.PHONY : ClangNodes.cpp.s

ClangastDumperAttr.o: ClangastDumperAttr.cpp.o

.PHONY : ClangastDumperAttr.o

# target to build an object file
ClangastDumperAttr.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangastDumperAttr.cpp.o
.PHONY : ClangastDumperAttr.cpp.o

ClangastDumperAttr.i: ClangastDumperAttr.cpp.i

.PHONY : ClangastDumperAttr.i

# target to preprocess a source file
ClangastDumperAttr.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangastDumperAttr.cpp.i
.PHONY : ClangastDumperAttr.cpp.i

ClangastDumperAttr.s: ClangastDumperAttr.cpp.s

.PHONY : ClangastDumperAttr.s

# target to generate assembly for a file
ClangastDumperAttr.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClangastDumperAttr.cpp.s
.PHONY : ClangastDumperAttr.cpp.s

ClavaConstants.o: ClavaConstants.cpp.o

.PHONY : ClavaConstants.o

# target to build an object file
ClavaConstants.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaConstants.cpp.o
.PHONY : ClavaConstants.cpp.o

ClavaConstants.i: ClavaConstants.cpp.i

.PHONY : ClavaConstants.i

# target to preprocess a source file
ClavaConstants.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaConstants.cpp.i
.PHONY : ClavaConstants.cpp.i

ClavaConstants.s: ClavaConstants.cpp.s

.PHONY : ClavaConstants.s

# target to generate assembly for a file
ClavaConstants.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaConstants.cpp.s
.PHONY : ClavaConstants.cpp.s

ClavaDataDumper.o: ClavaDataDumper.cpp.o

.PHONY : ClavaDataDumper.o

# target to build an object file
ClavaDataDumper.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumper.cpp.o
.PHONY : ClavaDataDumper.cpp.o

ClavaDataDumper.i: ClavaDataDumper.cpp.i

.PHONY : ClavaDataDumper.i

# target to preprocess a source file
ClavaDataDumper.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumper.cpp.i
.PHONY : ClavaDataDumper.cpp.i

ClavaDataDumper.s: ClavaDataDumper.cpp.s

.PHONY : ClavaDataDumper.s

# target to generate assembly for a file
ClavaDataDumper.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumper.cpp.s
.PHONY : ClavaDataDumper.cpp.s

ClavaDataDumperAttrs.o: ClavaDataDumperAttrs.cpp.o

.PHONY : ClavaDataDumperAttrs.o

# target to build an object file
ClavaDataDumperAttrs.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperAttrs.cpp.o
.PHONY : ClavaDataDumperAttrs.cpp.o

ClavaDataDumperAttrs.i: ClavaDataDumperAttrs.cpp.i

.PHONY : ClavaDataDumperAttrs.i

# target to preprocess a source file
ClavaDataDumperAttrs.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperAttrs.cpp.i
.PHONY : ClavaDataDumperAttrs.cpp.i

ClavaDataDumperAttrs.s: ClavaDataDumperAttrs.cpp.s

.PHONY : ClavaDataDumperAttrs.s

# target to generate assembly for a file
ClavaDataDumperAttrs.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperAttrs.cpp.s
.PHONY : ClavaDataDumperAttrs.cpp.s

ClavaDataDumperDecls.o: ClavaDataDumperDecls.cpp.o

.PHONY : ClavaDataDumperDecls.o

# target to build an object file
ClavaDataDumperDecls.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperDecls.cpp.o
.PHONY : ClavaDataDumperDecls.cpp.o

ClavaDataDumperDecls.i: ClavaDataDumperDecls.cpp.i

.PHONY : ClavaDataDumperDecls.i

# target to preprocess a source file
ClavaDataDumperDecls.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperDecls.cpp.i
.PHONY : ClavaDataDumperDecls.cpp.i

ClavaDataDumperDecls.s: ClavaDataDumperDecls.cpp.s

.PHONY : ClavaDataDumperDecls.s

# target to generate assembly for a file
ClavaDataDumperDecls.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperDecls.cpp.s
.PHONY : ClavaDataDumperDecls.cpp.s

ClavaDataDumperStmts.o: ClavaDataDumperStmts.cpp.o

.PHONY : ClavaDataDumperStmts.o

# target to build an object file
ClavaDataDumperStmts.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperStmts.cpp.o
.PHONY : ClavaDataDumperStmts.cpp.o

ClavaDataDumperStmts.i: ClavaDataDumperStmts.cpp.i

.PHONY : ClavaDataDumperStmts.i

# target to preprocess a source file
ClavaDataDumperStmts.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperStmts.cpp.i
.PHONY : ClavaDataDumperStmts.cpp.i

ClavaDataDumperStmts.s: ClavaDataDumperStmts.cpp.s

.PHONY : ClavaDataDumperStmts.s

# target to generate assembly for a file
ClavaDataDumperStmts.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperStmts.cpp.s
.PHONY : ClavaDataDumperStmts.cpp.s

ClavaDataDumperTypes.o: ClavaDataDumperTypes.cpp.o

.PHONY : ClavaDataDumperTypes.o

# target to build an object file
ClavaDataDumperTypes.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperTypes.cpp.o
.PHONY : ClavaDataDumperTypes.cpp.o

ClavaDataDumperTypes.i: ClavaDataDumperTypes.cpp.i

.PHONY : ClavaDataDumperTypes.i

# target to preprocess a source file
ClavaDataDumperTypes.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperTypes.cpp.i
.PHONY : ClavaDataDumperTypes.cpp.i

ClavaDataDumperTypes.s: ClavaDataDumperTypes.cpp.s

.PHONY : ClavaDataDumperTypes.s

# target to generate assembly for a file
ClavaDataDumperTypes.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDataDumperTypes.cpp.s
.PHONY : ClavaDataDumperTypes.cpp.s

ClavaDecl.o: ClavaDecl.cpp.o

.PHONY : ClavaDecl.o

# target to build an object file
ClavaDecl.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDecl.cpp.o
.PHONY : ClavaDecl.cpp.o

ClavaDecl.i: ClavaDecl.cpp.i

.PHONY : ClavaDecl.i

# target to preprocess a source file
ClavaDecl.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDecl.cpp.i
.PHONY : ClavaDecl.cpp.i

ClavaDecl.s: ClavaDecl.cpp.s

.PHONY : ClavaDecl.s

# target to generate assembly for a file
ClavaDecl.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/ClavaDecl.cpp.s
.PHONY : ClavaDecl.cpp.s

TypeMarker.o: TypeMarker.cpp.o

.PHONY : TypeMarker.o

# target to build an object file
TypeMarker.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/TypeMarker.cpp.o
.PHONY : TypeMarker.cpp.o

TypeMarker.i: TypeMarker.cpp.i

.PHONY : TypeMarker.i

# target to preprocess a source file
TypeMarker.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/TypeMarker.cpp.i
.PHONY : TypeMarker.cpp.i

TypeMarker.s: TypeMarker.cpp.s

.PHONY : TypeMarker.s

# target to generate assembly for a file
TypeMarker.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/TypeMarker.cpp.s
.PHONY : TypeMarker.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ClangAstDumper.dir/build.make CMakeFiles/ClangAstDumper.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ClangAstDumper"
	@echo "... edit_cache"
	@echo "... ChildrenVisitorAttrs.o"
	@echo "... ChildrenVisitorAttrs.i"
	@echo "... ChildrenVisitorAttrs.s"
	@echo "... ChildrenVisitorDecls.o"
	@echo "... ChildrenVisitorDecls.i"
	@echo "... ChildrenVisitorDecls.s"
	@echo "... ChildrenVisitorExtras.o"
	@echo "... ChildrenVisitorExtras.i"
	@echo "... ChildrenVisitorExtras.s"
	@echo "... ChildrenVisitorStmts.o"
	@echo "... ChildrenVisitorStmts.i"
	@echo "... ChildrenVisitorStmts.s"
	@echo "... ChildrenVisitorTypes.o"
	@echo "... ChildrenVisitorTypes.i"
	@echo "... ChildrenVisitorTypes.s"
	@echo "... ClangAst.o"
	@echo "... ClangAst.i"
	@echo "... ClangAst.s"
	@echo "... ClangAstDumper.o"
	@echo "... ClangAstDumper.i"
	@echo "... ClangAstDumper.s"
	@echo "... ClangAstDumperDecls.o"
	@echo "... ClangAstDumperDecls.i"
	@echo "... ClangAstDumperDecls.s"
	@echo "... ClangAstDumperExprs.o"
	@echo "... ClangAstDumperExprs.i"
	@echo "... ClangAstDumperExprs.s"
	@echo "... ClangAstDumperExtra.o"
	@echo "... ClangAstDumperExtra.i"
	@echo "... ClangAstDumperExtra.s"
	@echo "... ClangAstDumperStmts.o"
	@echo "... ClangAstDumperStmts.i"
	@echo "... ClangAstDumperStmts.s"
	@echo "... ClangAstDumperTypes.o"
	@echo "... ClangAstDumperTypes.i"
	@echo "... ClangAstDumperTypes.s"
	@echo "... ClangEnums.o"
	@echo "... ClangEnums.i"
	@echo "... ClangEnums.s"
	@echo "... ClangNodes.o"
	@echo "... ClangNodes.i"
	@echo "... ClangNodes.s"
	@echo "... ClangastDumperAttr.o"
	@echo "... ClangastDumperAttr.i"
	@echo "... ClangastDumperAttr.s"
	@echo "... ClavaConstants.o"
	@echo "... ClavaConstants.i"
	@echo "... ClavaConstants.s"
	@echo "... ClavaDataDumper.o"
	@echo "... ClavaDataDumper.i"
	@echo "... ClavaDataDumper.s"
	@echo "... ClavaDataDumperAttrs.o"
	@echo "... ClavaDataDumperAttrs.i"
	@echo "... ClavaDataDumperAttrs.s"
	@echo "... ClavaDataDumperDecls.o"
	@echo "... ClavaDataDumperDecls.i"
	@echo "... ClavaDataDumperDecls.s"
	@echo "... ClavaDataDumperStmts.o"
	@echo "... ClavaDataDumperStmts.i"
	@echo "... ClavaDataDumperStmts.s"
	@echo "... ClavaDataDumperTypes.o"
	@echo "... ClavaDataDumperTypes.i"
	@echo "... ClavaDataDumperTypes.s"
	@echo "... ClavaDecl.o"
	@echo "... ClavaDecl.i"
	@echo "... ClavaDecl.s"
	@echo "... TypeMarker.o"
	@echo "... TypeMarker.i"
	@echo "... TypeMarker.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

