package pt.up.fe.specs.clava.weaver;

import org.lara.langspec2.dsl.WeaverSpec;
import org.lara.langspec2.types.JpDataType.BoundKind;
import org.lara.langspec2.types.JpDataType.WildcardType;

/**
 * Weaver specification for the Clava C/C++ weaver, translated from the XML
 * specification files
 * (joinPointModel.xml and artifacts.xml) into the Java DSL.
 */
public class CxxSpec extends WeaverSpec {

    @Override
    public void define() {
        weaverName("CxxWeaver");
        packageName("pt.up.fe.specs.clava.weaver");
        rootJoinPoint("program");

        // =====================================================================
        // Enum definitions
        // =====================================================================

        enumDef("StorageClass")
                .value("NONE")
                .value("AUTO")
                .value("EXTERN")
                .value("PRIVATE_EXTERN")
                .value("REGISTER")
                .value("STATIC")
                .end();

        enumDef("Relation")
                .value("LE")
                .value("LT")
                .value("GE")
                .value("GT")
                .value("EQ")
                .value("NE")
                .end();

        enumDef("LoopKind")
                .value("for")
                .value("while")
                .value("dowhile")
                .value("foreach")
                .end();

        enumDef("ExpressionUse")
                .value("read")
                .value("write")
                .value("readwrite")
                .end();

        enumDef("OpKind")
                .value("ptr_mem_d")
                .value("ptr_mem_i")
                .value("mul")
                .value("div")
                .value("rem")
                .value("add")
                .value("sub")
                .value("shl")
                .value("shr")
                .value("cmp")
                .value("lt")
                .value("gt")
                .value("le")
                .value("ge")
                .value("eq")
                .value("ne")
                .value("and")
                .value("xor")
                .value("or")
                .value("l_and")
                .value("l_or")
                .value("assign")
                .value("mul_assign")
                .value("div_assign")
                .value("rem_assign")
                .value("add_assign")
                .value("sub_assign")
                .value("shl_assign")
                .value("shr_assign")
                .value("and_assign")
                .value("xor_assign")
                .value("or_assign")
                .value("comma")
                .value("post_inc")
                .value("post_dec")
                .value("pre_inc")
                .value("pre_dec")
                .value("addr_of")
                .value("deref")
                .value("plus")
                .value("minus")
                .value("not")
                .value("l_not")
                .value("real")
                .value("imag")
                .value("extension")
                .value("cowait")
                .value("ternary")
                .end();

        enumDef("WrapperStatementKind")
                .value("comment")
                .value("pragma")
                .end();

        // =====================================================================
        // Global attributes (weaver-specific, not in BaseJoinPointSpec)
        // Excludes base contract: dump, joinPointType, node, self, super,
        // children, descendants, scopeNodes, insert, toString, equals, instanceOf
        // =====================================================================

        global()
                .attribute("root", jpRef("program"), "Returns the 'program' joinpoint at the root of the hierarchy")
                .attribute("getAncestor")
                    .tooltip("Looks for an ancestor joinpoint name, walking back on the AST")
                    .param("type", STRING)
                    .returns(jpRef("joinpoint"))
                .attribute("getDescendants")
                    .tooltip("Retrieves the descendants of the given type")
                    .param("type", STRING)
                    .returns(array(jpRef("joinpoint")))
                .attribute("getDescendantsAndSelf")
                    .tooltip("Retrieves the descendants of the given type, including the current joinpoint")
                    .param("type", STRING)
                    .returns(array(jpRef("joinpoint")))
                .attribute("getChainAncestor")
                    .tooltip("Looks for an ancestor joinpoint name, walking back on the joinpoint chain")
                    .param("type", STRING)
                    .returns(jpRef("joinpoint"))
                .attribute("getAstAncestor")
                    .tooltip("[DEPRECATED: Looks for an ancestor AST name, walking back on the AST]")
                    .param("type", STRING)
                    .returns(jpRef("joinpoint"))
                .attribute("contains")
                    .tooltip("Checks if the joinpoint contains the given joinpoint")
                    .param("jp", jpRef("joinpoint"))
                    .returns(BOOLEAN)
                .attribute("hasParent", BOOLEAN)
                .attribute("getFirstJp")
                    .tooltip("Retrieves the  first node of the given type in the descendants")
                    .param("type", STRING)
                    .returns(jpRef("joinpoint"))
                .attribute("endLine", INTEGER, "The ending line of the current node in the original code")
                .attribute("endColumn", INTEGER, "The ending column of the current node in the original code")
                .attribute("location", STRING, "A string with information about the file and code position of this node, if available")
                .attribute("filename", STRING, "The filename of the current node")
                .attribute("filepath", STRING, "The file path of the current node")
                .attribute("astId", STRING, "The AST ID of the current node")
                .attribute("ast", STRING, "String with a dump of the AST representation starting from this node. This representation corresponds to the internal Java representation of the ClavaAst, where the node names correspond to Java classes. To get an equivalent representation with join point names, use the attribute 'dump'")
                .attribute("type", jpRef("type"))
                .attribute("hasType", BOOLEAN, "True, if the join point has a type")
                .attribute("bitWidth", INTEGER, "The bit width of the type returned by this join point, in relation to the definitions of its Translation Unit, or undefined if there is no type or bitwidth defined, or if the join point is not in a TranslationUnit")
                .attribute("astName", STRING, "The name of the Java class of this node, which is similar to the equivalent node in Clang AST")
                .attribute("astNumChildren", INT, "Returns the number of children of the node, considering null nodes")
                .attribute("astChildren", array(jpRef("joinpoint")), "Returns an array with the children of the node, considering null nodes")
                .attribute("getAstChild")
                    .tooltip("Returns the child of the node at the given index, considering null nodes") 
                    .param("index", INT)
                    .returns(jpRef("joinpoint"))
                .attribute("numChildren", INT, "Returns the number of children of the node, ignoring null nodes")
                .attribute("getChild")
                    .tooltip("Returns the child of the node at the given index, ignoring null nodes")
                    .param("index", INT)
                    .returns(jpRef("joinpoint"))
                .attribute("siblingsLeft", array(jpRef("joinpoint")), "Returns an array with the siblings that came before this node")
                .attribute("siblingsRight", array(jpRef("joinpoint")), "Returns an array with the siblings that come after this node")
                .attribute("leftJp", jpRef("joinpoint"), "Returns the node that came before this node, or undefined if there is none")
                .attribute("rightJp", jpRef("joinpoint"), "Returns the node that comes after this node, or undefined if there is none")
                .attribute("astIsInstance")
                    .tooltip("True, if this node is a Java instance of the given name, which corresponds to a simple Java class name of an AST node. For an equivalent function for join point names, use 'instanceOf(joinPointName)'")
                    .param("className", STRING)
                    .returns(BOOLEAN)
                .attribute("hasNode")
                    .tooltip("True, if the given join point or AST node is the same (== test) as the current join point AST node")
                    .param("nodeOrJp", OBJECT)
                    .returns(BOOLEAN)
                .attribute("chain", array(STRING), "String list of the names of the join points that form a path from the root to this node")
                .attribute("javaFields", array(STRING), "[DEPRECATED: used attribute 'keys' instead, together with 'getValue'] The names of the Java fields of this node. Can be used as key of the attribute 'javaValue'")
                .attribute("getJavaFieldType")
                    .tooltip("String with the full Java class name of the type of the Java field with the provided name")
                    .param("fieldName", STRING)
                    .returns(STRING)
                .attribute("isInsideLoopHeader", BOOLEAN, "True, if the join point is inside a loop header (e.g., for, while)")
                .attribute("isInsideHeader", BOOLEAN, "True, if the join point is inside a header (e.g., function declaration)")
                .attribute("isInSystemHeader", BOOLEAN, "True, if the join point is inside a system header (e.g., #include <stdio.h>)")
                .attribute("getUserField")
                    .tooltip("Retrives values that have been associated to nodes of the AST with 'setUserField'")
                    .param("fieldName", STRING)
                    .returns(OBJECT)
                .attribute("parentRegion", jpRef("joinpoint"), "Returns the parent region of this join point, or undefined if there is none")
                .attribute("currentRegion", jpRef("joinpoint"), "Returns the current region of this join point")
                .attribute("pragmas", array(jpRef("pragma")), "Returns the pragmas associated with this join point")
                .attribute("data", OBJECT, "JS object associated with this node, containing parsed data of #pragma clava data when the node can be a target of pragmas. This is a special object, managed internally, and cannot be reassigned, to change its contents requires using key-value pairs. If the node can be the target of a pragma, the information stored in this object is persisted between rebuilds.")
                .attribute("keys", array(STRING), "A list of the properties currently supported by this node. Can be used as parameter of the attribute 'getValue'")
                .attribute("getValue")
                    .tooltip("Returns the value of the property with the given name")
                    .param("key", STRING)
                    .returns(OBJECT)
                .attribute("getKeyType")
                    .tooltip("Returns the type of the property with the given name")
                    .param("key", STRING)
                    .returns(OBJECT)
                .attribute("isMacro", BOOLEAN, "True if any descendant or the node itself was defined as a macro")
                .attribute("firstChild", jpRef("joinpoint"), "Returns the first child of this node, or undefined if it has no child")
                .attribute("lastChild", jpRef("joinpoint"), "Returns the last child of this node, or undefined if it has no child")
                .attribute("hasChildren", BOOLEAN, "True if the node has any children")
                .attribute("isCilk", BOOLEAN, "True if the node is a Cilk node")
                .attribute("depth", INT, "Returns the depth of this node in the AST. Root=0")
                .attribute("jpId", STRING, "Returns the ID of this join point. The ID is based on the position of the node in the code, and should remain stable between compilations (warning: only a few nodes - file, function, loop - currently support it)")
                .attribute("stmt", jpRef("statement"), "Converts this join point to a statement, or returns undefined if it was not possible")
                .attribute("inlineComments", array(jpRef("comment")), "Returns comments that are not explicitly in the AST, but embedded in other nodes")
                .attribute("originNode", jpRef("joinpoint"), "If this join point was not originally from the parsed AST, returns the first join point of the original AST that contributed to its origin")
                .attribute("jpFields")
                    .tooltip("List with the values of fields that are join points, recursively")
                    .param("recursive", BOOLEAN, "false")
                    .returns(array(jpRef("joinpoint")))
                .action("replaceWith")
                    .tooltip("Replaces this node with the given node")
                    .param("node", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("replaceWith")
                    .tooltip("Overload that accepts a string")
                    .param("node", STRING)
                    .returns(jpRef("joinpoint"))
                .action("replaceWith")
                    .tooltip("Overload that accepts a list of joinpoints")
                    .param("node", array(jpRef("joinpoint")))
                    .returns(jpRef("joinpoint"))
                .action("replaceWithStrings")
                    .tooltip("Overload that accepts a list of strings")
                    .param("node", array(STRING))
                    .returns(jpRef("joinpoint"))
                .action("insertBefore")
                    .tooltip("Inserts the given joinpoint before this joinpoint")
                    .param("node", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("insertBefore")
                    .tooltip("Overload that accepts a string")
                    .param("node", STRING)
                    .returns(jpRef("joinpoint"))
                .action("insertAfter")
                    .tooltip("Inserts the given joinpoint after this joinpoint")
                    .param("node", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("insertAfter")
                    .tooltip("Overload that accepts a string")
                    .param("node", STRING)
                    .returns(jpRef("joinpoint"))
                .action("detach")
                    .tooltip("Removes the node associated to this joinpoint from the AST")
                    .returns(jpRef("joinpoint"))
                .action("setType")
                    .tooltip("Sets the type of a node, if it has a type")
                    .param("type", jpRef("type"))
                    .returns(VOID)
                .action("copy")
                    .tooltip("Performs a copy of the node and its children, but not of the nodes in its fields")
                    .returns(jpRef("joinpoint"))
                .action("deepCopy")
                    .tooltip("Performs a copy of the node and its children, including the nodes in their fields (only the first level of field nodes, this function is not recursive)")
                    .returns(jpRef("joinpoint"))
                .action("setUserField")
                    .tooltip("Associates arbitrary values to nodes of the AST")
                    .param("fieldName", STRING)
                    .param("value", OBJECT)
                    .returns(OBJECT)
                .action("setUserField")
                    .tooltip("Overload that accepts a map")
                    .param("fieldNameAndValue", map(STRING, new WildcardType(BoundKind.UNBOUNDED, null)))
                    .returns(OBJECT)
                .action("setValue")
                    .tooltip("Sets the value associated with the given property key")
                    .param("key", STRING)
                    .param("value", OBJECT)
                    .returns(jpRef("joinpoint"))
                .action("messageToUser")
                    .tooltip("Adds a message that will be printed to the user after weaving finishes. Identical messages are removed")
                    .param("message", STRING)
                    .returns(VOID)
                .action("removeChildren")
                    .tooltip("Removes the children of this node")
                    .returns(VOID)
                .action("setFirstChild")
                    .tooltip("Replaces the first child, or inserts the join point if no child is present. Returns the replaced child, or undefined if there was no child present")
                    .param("node", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("setLastChild")
                    .tooltip("Replaces the last child, or inserts the join point if no child is present. Returns the replaced child, or undefined if there was no child present")
                    .param("node", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("toComment")
                    .tooltip("Replaces this join point with a comment with the same contents as .code")
                    .param("prefix", STRING, "\"\"")
                    .param("suffix", STRING, "\"\"")
                    .returns(jpRef("joinpoint"))
                .action("setInlineComments")
                    .tooltip("Sets the comments that are embedded in a node")
                    .param("comments", array(STRING))
                    .returns(VOID)
                .action("setInlineComments")
                    .tooltip("Sets the comments that are embedded in a node")
                    .param("comments", STRING)
                    .returns(VOID)
                .action("setData")
                    .tooltip("Setting data directly is not supported, this action just emits a warning and does nothing")
                    .param("source", OBJECT)
                    .returns(VOID)
                .action("dataClear")
                    .tooltip("Clears all properties from the .data object")
                    .returns(VOID);

        // =====================================================================
        // Join point definitions
        // =====================================================================

        // --- Utility join points ---

        joinPoint("empty")
                .tooltip("Utility joinpoint, to represent empty nodes when directly accessing the tree");

        // --- Program / File ---

        joinPoint("program")
                .tooltip("Represents the complete program and is the top-most joinpoint in the hierarchy")
                .defaultAttribute("name")
                .attribute("name", STRING)
                .attribute("isCxx", BOOLEAN, "True if the program was compiled with a C++ standard")
                .attribute("standard", STRING, "The name of the standard (e.g., c99, c++11)")
                .attribute("stdFlag", STRING, "The flag of the standard (e.g., -std=c++11)")
                .attribute("defaultFlags", array(STRING))
                .attribute("userFlags", array(STRING))
                .attribute("includeFolders", array(STRING))
                .attribute("baseFolder", STRING)
                .attribute("weavingFolder", STRING)
                .attribute("extraSources", array(STRING), "Paths to sources that the current program depends on")
                .attribute("extraIncludes", array(STRING), "Paths to includes that the current program depends on")
                .attribute("extraProjects", array(STRING), "Paths to folders of projects that the current program depends on")
                .attribute("extraLibs", array(STRING), "Link libraries of external projects the current program depends on")
                .attribute("main", jpRef("function"), "A function join point with the main function of the program, if one is available")
                .attribute("files", array(jpRef("file")), "The files of the program")
                .action("rebuild")
                    .tooltip("Recompiles the program currently represented by the AST, transforming literal code into AST nodes. Returns true if all files could be parsed correctly, or false otherwise")
                    .returns(BOOLEAN)
                .action("rebuildFuzzy")
                    .tooltip("Similar to rebuild, but tries to fix compilation errors. Resulting program may not represent the originally intended functionality")
                    .returns(VOID)
                .action("addFile")
                    .tooltip("Adds a file join point to the current program")
                    .param("file", jpRef("file"))
                    .returns(jpRef("joinpoint"))
                .action("addFileFromPath")
                    .tooltip("Adds a file join point to the current program, from the given path, which can be either a Java File or a String")
                    .param("filepath", OBJECT)
                    .returns(jpRef("joinpoint"))
                .action("push")
                    .tooltip("Creates a copy of the current AST and pushes it to the top of the AST stack")
                    .returns(VOID)
                .action("pop")
                    .tooltip("Discards the AST at the top of the AST stack")
                    .returns(VOID)
                .action("addExtraInclude")
                    .tooltip("Adds a path to an include that the current program depends on")
                    .param("path", STRING)
                    .returns(VOID)
                .action("addExtraIncludeFromGit")
                    .tooltip("Adds a path based on a git repository to an include that the current program depends on")
                    .param("gitRepo", STRING)
                    .param("path", STRING, "null")
                    .returns(VOID)
                .action("addExtraSource")
                    .tooltip("Adds a path to a source that the current program depends on")
                    .param("path", STRING)
                    .returns(VOID)
                .action("addExtraSourceFromGit")
                    .tooltip("Adds a path based on a git repository to a source that the current program depends on")
                    .param("gitRepo", STRING)
                    .param("path", STRING, "null")
                    .returns(VOID)
                .action("addProjectFromGit")
                    .tooltip("Adds a path based on a git repository to a project that the current program depends on")
                    .param("gitRepo", STRING)
                    .param("libs", array(STRING))
                    .param("path", STRING, "null")
                    .returns(VOID)
                .action("addExtraLib")
                    .tooltip("Adds a library (e.g., -pthreads) that the current program depends on")
                    .param("lib", STRING)
                    .returns(VOID)
                .action("atexit")
                    .tooltip("Registers a function to be executed when the program exits")
                    .param("function", jpRef("function"))
                    .returns(VOID);

        joinPoint("file")
                .tooltip("Represents a source file (.c, .cpp, .cl, etc)")
                .defaultAttribute("name")
                .attribute("name", STRING)
                .attribute("file", OBJECT, "The Java File object associated with this file")
                .attribute("hasMain", BOOLEAN, "True if this file has the main function as a descendant")
                .attribute("path", STRING, "The folder path for this file")
                .attribute("relativeFilepath", STRING, "The file path relative to the base folder of the program")
                .attribute("relativeFolderpath", STRING, "The folder path relative to the base folder of the program")
                .attribute("baseSourcePath", STRING, "The base source path for this file")
                .attribute("isCxx", BOOLEAN, "True if this file is a being parsed as a C++ file")
                .attribute("isHeader", BOOLEAN, "True if this file is a header file")
                .attribute("isOpenCL", BOOLEAN, "True if this file is an OpenCL file")
                .attribute("getDestinationFilepath")
                    .tooltip("The complete path to the file that will be generated by the weaver, given a destination folder")
                    .param("destinationFolderpath", STRING, "null")
                    .returns(STRING)
                .attribute("sourceFoldername", STRING, "The name of the source folder of this file, or undefined if it has none")
                .attribute("hasParsingErrors", BOOLEAN, "True if there were errors during the parsing of this file")
                .attribute("errorOutput", STRING, "The error output produced during the parsing of this file, if any")
                .attribute("includes", array(jpRef("include")), "The include directives in this file")
                .action("addInclude")
                    .tooltip("Adds an include to the current file. If the file already has the include, it does nothing")
                    .param("name", STRING)
                    .param("isAngled", BOOLEAN, "false")
                    .returns(VOID)
                .action("addIncludeJp")
                    .tooltip("Overload of addInclude which accepts a join point")
                    .param("jp", jpRef("joinpoint"))
                    .returns(VOID)
                .action("addCInclude")
                    .tooltip("Adds a C include to the current file. If the file already has the include, it does nothing")
                    .param("name", STRING)
                    .param("isAngled", BOOLEAN, "false")
                    .returns(VOID)
                .action("addGlobal")
                    .tooltip("Adds a global variable to this file")
                    .param("name", STRING)
                    .param("type", jpRef("joinpoint"))
                    .param("initValue", STRING)
                    .returns(jpRef("vardecl"))
                .action("write")
                    .tooltip("Writes the code of this file to a given folder")
                    .param("destinationFoldername", STRING)
                    .returns(STRING)
                .action("setName")
                    .tooltip("Changes the name of the file")
                    .param("filename", STRING)
                    .returns(VOID)
                .action("rebuild")
                    .tooltip("Recompiles only this file, returns a join point to the new recompiled file, or throws an exception if a problem happens")
                    .returns(jpRef("file"))
                .action("insertBegin")
                    .tooltip("Adds the node in the join point to the start of the file")
                    .param("node", jpRef("joinpoint"))
                    .returns(VOID)
                .action("insertBegin")
                    .tooltip("Adds the String as a Decl to the end of the file")
                    .param("code", STRING)
                    .returns(VOID)
                .action("insertEnd")
                    .tooltip("Adds the node in the join point to the end of the file")
                    .param("node", jpRef("joinpoint"))
                    .returns(VOID)
                .action("insertEnd")
                    .tooltip("Adds the String as a Decl to the end of the file")
                    .param("code", STRING)
                    .returns(VOID)
                .action("addFunction")
                    .tooltip("Adds a function to the file that returns void and has no parameters")
                    .param("name", STRING)
                    .returns(jpRef("joinpoint"))
                .action("setRelativeFolderpath")
                    .tooltip("Sets the path to the folder of the source file relative to the base source path")
                    .param("path", STRING)
                    .returns(VOID);

        // --- Declarations ---

        joinPoint("decl")
                .tooltip("Represents one declaration (e.g., int foo(){return 0;}) or definition (e.g., int foo();)")
                .attribute("attrs", array(jpRef("attribute")), "The attributes of this declaration (e.g. Pure, CUDAGlobal), if any");

        joinPoint("namedDecl").extending("decl")
                .tooltip("Represents a decl with a name")
                .defaultAttribute("name")
                .attribute("name", STRING)
                .attribute("isPublic", BOOLEAN)
                .attribute("qualifiedPrefix", STRING)
                .attribute("qualifiedName", STRING)
                .action("setName")
                    .tooltip("Sets the name of this namedDecl")
                    .param("name", STRING)
                    .returns(VOID)
                .action("setQualifiedPrefix")
                    .tooltip("Sets the qualified prefix of this namedDecl")
                    .param("qualifiedPrefix", STRING)
                    .returns(VOID)
                .action("setQualifiedName")
                    .tooltip("Sets the qualified name of this namedDecl (changes both the name and qualified prefix)")
                    .param("name", STRING)
                    .returns(VOID);

        joinPoint("declarator").extending("namedDecl")
                .tooltip("Represents a decl that comes from a declarator (e.g., function, field, variable)");

        joinPoint("include").extending("decl")
                .tooltip("Represents an include directive (e.g., #include <stdio.h>)")
                .defaultAttribute("name")
                .attribute("name", STRING)
                .attribute("isAngled", BOOLEAN, "True if the include is angled (e.g., #include <stdio.h>) instead of quoted (e.g., #include \"myheader.h\")")
                .attribute("relativeFolderpath", STRING, "The path to the folder of the source file of the include, relative to the name of the include");

        joinPoint("record").extending("namedDecl")
                .tooltip("Represents a record declaration (struct, union, or class)")
                .attribute("kind", STRING)
                .attribute("fields", array(jpRef("field")))
                .attribute("functions", array(jpRef("function")))
                .attribute("isImplementation", BOOLEAN, "True if this record declaration is an implementation (i.e., it has a body) instead of just a forward declaration")
                .attribute("isPrototype", BOOLEAN, "True if this record declaration is a prototype (i.e., it has no body) instead of an implementation")
                .action("addField")
                    .tooltip("Adds a field to a record (struct, class)")
                    .param("field", jpRef("field"))
                    .returns(VOID);

        joinPoint("field").extending("declarator")
                .tooltip("Represents a member of a struct/union/class");

        joinPoint("struct").extending("record")
                .tooltip("Represents a struct declaration");

        joinPoint("class").extending("record")
                .tooltip("Represents a C++ class declaration")
                .defaultAttribute("name")
                .attribute("methods", array(jpRef("method")), "The methods of this class")
                .attribute("bases", array(jpRef("class")), "The base classes of this class")
                .attribute("allMethods", array(jpRef("method")), "The methods of this class and its base classes")
                .attribute("allBases", array(jpRef("class")), "The base classes of this class and its base classes")
                .attribute("isAbstract", BOOLEAN, "True if this class contains at least one pure function")
                .attribute("isInterface", BOOLEAN, "True if this class contains only pure functions")
                .attribute("prototypes", array(jpRef("class")), "The prototypes (or declarations) of this class present in the AST, if any")
                .attribute("implementation", jpRef("class"), "The implementation (or definition) of this class present in the AST, or undefined if none is found")
                .attribute("canonical", jpRef("class"), "Class join points can either represent declarations or definitions, returns the definition of this class, if present, or the first declaration, if only declarations are present")
                .attribute("isCanonical", BOOLEAN, "True if this class join point is the canonical one, which is the definition if it is present, or the first declaration if only declarations are present")
                .action("addMethod")
                    .tooltip("Adds a method to a class. If the given method has a definition, creates an equivalent declaration and adds it to the class, otherwise simply adds the declaration to the class. In both cases, the declaration is only added to the class if there is no declaration already with the same signature")
                    .param("method", jpRef("method"))
                    .returns(VOID);

        joinPoint("vardecl").extending("declarator")
                .tooltip("Represents a variable declaration or definition")
                .defaultAttribute("name")
                .attribute("hasInit", BOOLEAN, "True if this variable declaration has an initializer")
                .attribute("init", jpRef("expression"), "The initializer of this variable declaration, if it has one")
                .attribute("initStyle", STRING, "The initialization style of this vardecl, which can be no_init, cinit, callinit, listinit")
                .attribute("isParam", BOOLEAN, "True if this variable declaration is a function parameter")
                .attribute("storageClass", enumRef("StorageClass"), "The storage class of this variable declaration. Can be 'none', 'extern', 'static', '__private_extern__', 'auto' or 'register'")
                .attribute("isGlobal", BOOLEAN, "True if this variable declaration is global. This includes all global variables as well as static variables declared within a function.")
                .attribute("definition", jpRef("vardecl"), "The vardecl corresponding to the actual definition. For global variables, returns the vardecl of the file where it is actually defined (instead of the vardecl that defines an external link to the variable)")
                .action("setInit")
                    .tooltip("Sets the given expression as the initialization of this vardecl. If undefined is passed and vardecl already has an initialization, removes that initialization")
                    .param("init", jpRef("expression"))
                    .returns(VOID)
                .action("setInit")
                    .tooltip("Converts the given string to a literal expression and sets it as the initialization of this vardecl. If undefined is passed and vardecl already has an initialization, removes that initialization")
                    .param("init", STRING)
                    .returns(VOID)
                .action("removeInit")
                    .tooltip("If vardecl already has an initialization, removes it")
                    .param("removeConst", BOOLEAN, "true")
                    .returns(VOID)
                .action("varref")
                    .tooltip("Creates a new varref based on this vardecl")
                    .returns(jpRef("varref"))
                .action("setStorageClass")
                    .tooltip("Sets the storage class specifier, which can be none, extern, static, __private_extern__, auto")
                    .param("storageClass", enumRef("StorageClass"))
                    .returns(VOID);

        joinPoint("typedefNameDecl").extending("namedDecl")
                .tooltip("Base node for declarations which introduce a typedef-name");

        joinPoint("typedefDecl").extending("typedefNameDecl")
                .tooltip("Declaration of a typedef-name via the 'typedef' type specifier");

        joinPoint("enumDecl").extending("namedDecl")
                .tooltip("Represents an enum declaration")
                .attribute("enumerators", array(jpRef("enumeratorDecl")));

        joinPoint("enumeratorDecl").extending("namedDecl")
                .tooltip("Represents an enumerator in an enum");

        joinPoint("labelDecl").extending("namedDecl")
                .tooltip("Represents a label declaration")
                .attribute("labelStmt", jpRef("labelStmt"));

        joinPoint("accessSpecifier").extending("decl")
                .tooltip("Represents an access specifier (public:, private:, or protected:) in a class declaration")
                .defaultAttribute("kind")
                .attribute("kind", STRING, "The type of specifier. Can return 'public', 'protected', 'private' or 'none'");

        joinPoint("param").extending("vardecl")
                .tooltip("Represents a function parameter");

        joinPoint("function").extending("declarator")
                .tooltip("Represents a function declaration or definition")
                .attribute("hasDefinition", BOOLEAN, "[DEPRECATED: Use .isImplementation instead] True if this particular function join point has a body, false otherwise")
                .attribute("isImplementation", BOOLEAN, "True if this function join point is an implementation, false otherwise")
                .attribute("isPrototype", BOOLEAN, "True if this function join point is a prototype, false otherwise")
                .attribute("functionType", jpRef("functionType"), "The function type of this function, which includes the return type and the parameter types")
                .attribute("declarationJp", jpRef("function"), "Returns the first prototype of this function that could be found, or undefined if there is none")
                .attribute("declarationJps", array(jpRef("function")), "Returns the prototypes of this function that are present in the code. If there are none, returns an empty array")
                .attribute("definitionJp", jpRef("function"), "Returns the implementation of this function if there is one, or undefined otherwise")
                .attribute("getDeclaration")
                    .param("withReturnType", BOOLEAN)
                    .returns(STRING)
                .attribute("body", jpRef("scope"))
                .attribute("paramNames", array(STRING))
                .attribute("params", array(jpRef("param")))
                .attribute("id", STRING)
                .attribute("isInline", BOOLEAN)
                .attribute("isVirtual", BOOLEAN)
                .attribute("isModulePrivate", BOOLEAN)
                .attribute("isPure", BOOLEAN)
                .attribute("isDelete", BOOLEAN)
                .attribute("storageClass", enumRef("StorageClass"))
                .attribute("calls", array(jpRef("call")))
                .attribute("signature", STRING, "The signature of this function (e.g., name of the function, plus the parameters types)")
                .attribute("returnType", jpRef("type"))
                .attribute("isCudaKernel", BOOLEAN)
                .attribute("canonical", jpRef("function"), "Function join points can either represent declarations or definitions, returns the definition of this function, if present, or the first declaration, if only declarations are present")
                .attribute("isCanonical", BOOLEAN, "True, if this is the function returned by the 'canonical' attribute")
                .action("clone")
                    .tooltip("Clones this function assigning it a new name, inserts the cloned function after the original function. If the name is the same and the original method, automatically removes the cloned method from the class")
                    .param("newName", STRING)
                    .param("insert", BOOLEAN, "true")
                    .returns(jpRef("function"))
                .action("cloneOnFile")
                    .tooltip("Generates a clone of the provided function on a new file with the provided name (or with a weaver-generated name if one is not provided)")
                    .param("newName", STRING)
                    .param("fileName", STRING, "null")
                    .returns(jpRef("function"))
                .action("cloneOnFile")
                    .tooltip("Generates a clone of the provided function on a new file (with the provided join point)")
                    .param("newName", STRING)
                    .param("file", jpRef("file"))
                    .returns(jpRef("function"))
                .action("insertReturn")
                    .tooltip("Inserts the joinpoint before the return points of the function (return statements and implicitly, at the end of the function). Returns the last inserted node")
                    .param("code", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("insertReturn")
                    .tooltip("Inserts code as a literal statement before the return points of the function (return statements and implicitly, at the end of the function). Returns the last inserted node")
                    .param("code", STRING)
                    .returns(jpRef("joinpoint"))
                .action("setParams")
                    .tooltip("Sets the parameters of the function")
                    .param("params", array(jpRef("param")))
                    .returns(VOID)
                .action("setParamsFromStrings")
                    .tooltip("Overload that accepts strings that represent type-varname pairs (e.g., int param1)")
                    .param("params", array(STRING))
                    .returns(VOID)
                .action("setParam")
                    .tooltip("Sets the parameter of the function at the given position")
                    .param("index", INT)
                    .param("param", jpRef("param"))
                    .returns(VOID)
                .action("setParam")
                    .tooltip("Sets the parameter of the function at the given position")
                    .param("index", INT)
                    .param("name", STRING)
                    .param("type", jpRef("type"), "null")
                    .returns(VOID)
                .action("setBody")
                    .tooltip("Sets the body of the function")
                    .param("body", jpRef("scope"))
                    .returns(VOID)
                .action("newCall")
                    .tooltip("Creates a new call to this function")
                    .param("args", array(jpRef("joinpoint")))
                    .returns(jpRef("call"))
                .action("setFunctionType")
                    .tooltip("Sets the type of the function")
                    .param("functionType", jpRef("functionType"))
                    .returns(VOID)
                .action("setReturnType")
                    .tooltip("Sets the return type of the function")
                    .param("returnType", jpRef("type"))
                    .returns(VOID)
                .action("setParamType")
                    .tooltip("Sets the type of a parameter of the function")
                    .param("index", INT)
                    .param("newType", jpRef("type"))
                    .returns(VOID)
                .action("addParam")
                    .tooltip("Adds a new parameter to the function")
                    .param("param", jpRef("param"))
                    .returns(VOID)
                .action("addParam")
                    .tooltip("Adds a new parameter to the function")
                    .param("name", STRING)
                    .param("type", jpRef("type"), "null")
                    .returns(VOID)
                .action("setStorageClass")
                    .tooltip("Sets the storage class of this specific function decl. AUTO and REGISTER are not allowed for functions, and EXTERN is not allowed in function implementations, or function declarations that are in the same file as the implementation. Returns true if the storage class changed, false otherwise")
                    .param("storageClass", enumRef("StorageClass"))
                    .returns(BOOLEAN);

        joinPoint("method").extending("function")
                .tooltip("Represents a method in a class declaration")
                .defaultAttribute("name")
                .attribute("record", jpRef("class"))
                .action("removeRecord")
                    .tooltip("Removes the class of the method")
                    .returns(VOID);

        // --- Pragmas ---

        joinPoint("pragma")
                .tooltip("Represents a pragma in the code (e.g., #pragma kernel)")
                .defaultAttribute("name")
                .attribute("name", STRING, "The name of the pragma. E.g. for #pragma foo bar, returns 'foo'")
                .attribute("target", jpRef("joinpoint"), "The first node below the pragma that is not a comment or another pragma. Example of pragma targets are statements and declarations")
                .attribute("content", STRING, "Everything that is after the name of the pragma")
                .attribute("getTargetNodes")
                    .tooltip("All the nodes below the target node, including the target node, up until a pragma with the name given by argument 'endPragma'. If no end pragma is found, returns the same result as if not providing the argument")
                    .param("endPragma", STRING, "null")
                    .returns(array(jpRef("joinpoint")))
                .action("setName")
                    .param("name", STRING)
                    .returns(VOID)
                .action("setContent")
                    .param("content", STRING)
                    .returns(VOID);

        joinPoint("marker").extending("pragma")
                .tooltip(
                        "Represents a marker pragma, which is used to mark a specific node in the code (e.g., #pragma myMarker) and can be used to store custom data")
                .defaultAttribute("id")
                .attribute("id", STRING)
                .attribute("contents", jpRef("scope"), "The scope that is targeted by the marker");

        joinPoint("tag").extending("pragma")
                .tooltip("Represents a tag pragma, which is used to reference a specific node in the code")
                .defaultAttribute("id")
                .attribute("id", STRING);

        joinPoint("omp").extending("pragma")
                .tooltip("Represents an OpenMP pragma (e.g., #pragma omp parallel)")
                .defaultAttribute("kind")
                .attribute("kind", STRING, "The kind of the directive")
                .attribute("numThreads", STRING, "An integer expression, or undefined if no 'num_threads' clause is defined")
                .attribute("procBind", STRING, "One of 'master', 'close' or 'spread', or undefined if no 'proc_bind' clause is defined")
                .attribute("private", array(STRING), "The variable names of all private clauses, or empty array if no private clause is defined")
                .attribute("hasClause")
                    .tooltip("True if the directive has at least one clause of the given clause kind, false otherwise")
                    .param("clauseName", STRING)
                    .returns(BOOLEAN)
                .attribute("isClauseLegal")
                    .tooltip("True if the directive has the given clause kind, false otherwise")
                    .param("clauseName", STRING)
                    .returns(BOOLEAN)
                .attribute("clauseKinds", array(STRING), "The names of the kinds of all clauses in the pragma, or empty array if no clause is defined")
                .attribute("getReduction")
                    .tooltip("The variable names for the given reduction kind, or empty array if no reduction of that kind is defined")
                    .param("kind", STRING)
                    .returns(array(STRING))
                .attribute("reductionKinds", array(STRING), "The reduction kinds in the reductions clauses of the this pragma, or empty array if no reduction is defined")
                .attribute("default", STRING, "One of 'shared' or 'none', or undefined if no 'default' clause is defined")
                .attribute("firstprivate", array(STRING), "The variable names of all firstprivate clauses, or empty array if no firstprivate clause is defined")
                .attribute("lastprivate", array(STRING), "The variable names of all lastprivate clauses, or empty array if no lastprivate clause is defined")
                .attribute("shared", array(STRING), "The variable names of all shared clauses, or empty array if no shared clause is defined")
                .attribute("copyin", array(STRING), "The variable names of all copyin clauses, or empty array if no copyin clause is defined")
                .attribute("scheduleKind", STRING, "One of 'static', 'dynamic', 'guided', 'auto' or 'runtime', or undefined if no 'schedule' clause is defined")
                .attribute("scheduleChunkSize", STRING, "An integer expression, or undefined if no 'schedule' clause with chunk size is defined")
                .attribute("scheduleModifiers", array(STRING), "A list with possible values of 'monotonic', 'nonmonotonic' or 'simd', or undefined if no 'schedule' clause with modifiers is defined")
                .attribute("collapse", STRING, "An integer expression, or undefined if no 'collapse' clause is defined")
                .attribute("ordered", STRING, "An integer expression, or undefined if no 'ordered' clause with a parameter is defined")
                .action("setKind")
                    .tooltip("Sets the directive kind of the OpenMP pragma. Any unsupported clauses will be discarded")
                    .param("directiveKind", STRING)
                    .returns(VOID)
                .action("removeClause")
                    .tooltip("Removes any clause of the given kind from the OpenMP pragma")
                    .param("clauseKind", STRING)
                    .returns(VOID)
                .action("setNumThreads")
                    .tooltip("Sets the value of the num_threads clause of an OpenMP pragma")
                    .param("newExpr", STRING)
                    .returns(VOID)
                .action("setProcBind")
                    .tooltip("Sets the value of the proc_bind clause of an OpenMP pragma")
                    .param("newBind", STRING)
                    .returns(VOID)
                .action("setPrivate")
                    .tooltip("Sets the variables of a private clause of an OpenMP pragma")
                    .param("newVariables", array(STRING))
                    .returns(VOID)
                .action("setReduction")
                    .tooltip("Sets the variables for a given kind of a reduction clause of an OpenMP pragma")
                    .param("kind", STRING)
                    .param("newVariables", array(STRING))
                    .returns(VOID)
                .action("setDefault")
                    .tooltip("Sets the value of the default clause of an OpenMP pragma")
                    .param("newDefault", STRING)
                    .returns(VOID)
                .action("setFirstprivate")
                    .tooltip("Sets the variables of a firstprivate clause of an OpenMP pragma")
                    .param("newVariables", array(STRING))
                    .returns(VOID)
                .action("setLastprivate")
                    .tooltip("Sets the variables of a lastprivate clause of an OpenMP pragma")
                    .param("newVariables", array(STRING))
                    .returns(VOID)
                .action("setShared")
                    .tooltip("Sets the variables of a shared clause of an OpenMP pragma")
                    .param("newVariables", array(STRING))
                    .returns(VOID)
                .action("setCopyin")
                    .tooltip("Sets the variables of a copyin clause of an OpenMP pragma")
                    .param("newVariables", array(STRING))
                    .returns(VOID)
                .action("setScheduleKind")
                    .tooltip("Sets the value of the schedule clause of an OpenMP pragma")
                    .param("scheduleKind", STRING)
                    .returns(VOID)
                .action("setScheduleChunkSize")
                    .tooltip("Sets the value of the chunk size in the schedule clause of an OpenMP pragma. Can only be called if there is already a schedule clause in the directive, otherwise throws an exception")
                    .param("chunkSize", STRING)
                    .returns(VOID)
                .action("setScheduleChunkSize")
                    .tooltip("Sets the value of the chunk size in the schedule clause of an OpenMP pragma. Can only be called if there is already a schedule clause in the directive, otherwise throws an exception")
                    .param("chunkSize", INT)
                    .returns(VOID)
                .action("setScheduleModifiers")
                    .tooltip("Sets the value of the modifiers in the schedule clause of an OpenMP pragma. Can only be called if there is already a schedule clause in the directive, otherwise throws an exception")
                    .param("modifiers", array(STRING))
                    .returns(VOID)
                .action("setCollapse")
                    .tooltip("Sets the value of the collapse clause of an OpenMP pragma")
                    .param("newExpr", STRING)
                    .returns(VOID)
                .action("setCollapse")
                    .tooltip("Sets the value of the collapse clause of an OpenMP pragma")
                    .param("newExpr", INT)
                    .returns(VOID)
                .action("setOrdered")
                    .tooltip("Sets the value of the ordered clause of an OpenMP pragma")
                    .param("parameters", STRING, "null")
                    .returns(VOID);

        // --- Statements ---

        joinPoint("statement")
                .attribute("isFirst", BOOLEAN)
                .attribute("isLast", BOOLEAN);

        joinPoint("scope").extending("statement")
                .tooltip("Represents a group of statements (e.g., function body, loop body, if/else body, etc.)")
                .attribute("getNumStatements")
                    .tooltip("The number of statements in the scope, including the statements inside the declaration and bodies of structures such as ifs and loops, and not considering comments and pragmas. If flat is true, does not consider the statements inside structures such as ifs and loops (e.g., a loop counts as one statement)")
                    .param("flat", BOOLEAN, "false")
                    .returns(LONG)
                .attribute("naked", BOOLEAN, "True if the scope does not have curly braces")
                .attribute("stmts", array(jpRef("statement")), "Returns the direct (children) statements of this scope")
                .attribute("allStmts", array(jpRef("statement")), "Returns the descendant statements of this scope, excluding other scopes, loops, ifs and wrapper statements")
                .attribute("firstStmt", jpRef("statement"), "Returns the first statement in the scope")
                .attribute("lastStmt", jpRef("statement"), "Returns the last statement in the scope")
                .attribute("owner", jpRef("joinpoint"), "The statement that owns the scope (e.g., function, loop...)")
                .action("insertBegin")
                    .param("node", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("insertBegin")
                    .param("code", STRING)
                    .returns(jpRef("joinpoint"))
                .action("insertEnd")
                    .param("node", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("insertEnd")
                    .param("code", STRING)
                    .returns(jpRef("joinpoint"))
                .action("insertReturn")
                    .tooltip("Inserts the joinpoint before the return points of the scope (return statements and implicitly, at the end of the scope). Returns the last inserted node")
                    .param("code", jpRef("joinpoint"))
                    .returns(jpRef("joinpoint"))
                .action("insertReturn")
                    .tooltip("Inserts the joinpoint before the return points of the scope (return statements and implicitly, at the end of the scope). Returns the last inserted node")
                    .param("code", STRING)
                    .returns(jpRef("joinpoint"))
                .action("addLocal")
                    .tooltip("Adds a new local variable to this scope")
                    .param("name", STRING)
                    .param("type", jpRef("joinpoint"))
                    .param("initValue", STRING, "null")
                    .returns(jpRef("joinpoint"))
                .action("setNaked")
                    .tooltip("Sets the 'naked' status of a scope (a scope is naked if it does not have curly braces)")
                    .param("isNaked", BOOLEAN)
                    .returns(VOID)
                .action("clear")
                    .tooltip("Clears the contents of this scope (untested)")
                    .returns(VOID)
                .action("cfg")
                    .tooltip("CFG tester")
                    .returns(STRING)
                .action("dfg")
                    .tooltip("DFG tester")
                    .returns(STRING);

        joinPoint("body").extending("scope");

        joinPoint("loop").extending("statement")
                .defaultAttribute("kind")
                .attribute("kind", enumRef("LoopKind"))
                .attribute("id", STRING, "Uniquely identifies the loop inside the program")
                .attribute("isInnermost", BOOLEAN)
                .attribute("isOutermost", BOOLEAN)
                .attribute("nestedLevel", INT)
                .attribute("controlVar", STRING)
                .attribute("controlVarref", jpRef("varref"))
                .attribute("rank", array(INT))
                .attribute("isParallel", BOOLEAN)
                .attribute("iterations", INTEGER)
                .attribute("iterationsExpr", jpRef("expression"))
                .attribute("isInterchangeable")
                    .tooltip("True if this loop can be interchanged with the given loop, which means that they are adjacent and have no data dependencies that would prevent their interchange. This is a conservative test.")
                    .param("otherLoop", jpRef("loop"))
                    .returns(BOOLEAN)
                .attribute("init", jpRef("statement"), "The statement of the loop initialization")
                .attribute("initValue", STRING, "The expression of the first value of the control variable (e.g. '0' in 'size_t i = 0;')")
                .attribute("cond", jpRef("statement"), "The statement of the loop condition")
                .attribute("step", jpRef("statement"), "The statement of the loop step")
                .attribute("endValue", STRING, "The expression of the last value of the control variable (e.g. '10' in 'size_t i = 0; i < 10; i++')")
                .attribute("stepValue", STRING, "The expression of the step value of the control variable (e.g. '1' in 'size_t i = 0; i < 10; i++')")
                .attribute("hasCondRelation", BOOLEAN, "True if the condition of the loop in the canonical format, and is one of: <, <=, >, >=")
                .attribute("condRelation", enumRef("Relation"))
                .attribute("body", jpRef("scope"))
                .action("setKind")
                    .tooltip("Sets the kind of the loop")
                    .param("kind", enumRef("LoopKind"))
                    .returns(VOID)
                .action("setInit")
                    .tooltip("Sets the init statement of the loop")
                    .param("initCode", STRING)
                    .returns(VOID)
                .action("setInitValue")
                    .tooltip("Sets the init value of the loop. Works with loops of kind 'for'")
                    .param("initCode", STRING)
                    .returns(VOID)
                .action("setEndValue")
                    .tooltip("Sets the end value of the loop. Works with loops of kind 'for'")
                    .param("initCode", STRING)
                    .returns(VOID)
                .action("setCond")
                    .tooltip("Sets the conditional statement of the loop. Works with loops of kind 'for'")
                    .param("condCode", STRING)
                    .returns(VOID)
                .action("setStep")
                    .tooltip("Sets the step statement of the loop. Works with loops of kind 'for'")
                    .param("stepCode", STRING)
                    .returns(VOID)
                .action("setIsParallel")
                    .tooltip("Sets the attribute 'isParallel' of the loop")
                    .param("isParallel", BOOLEAN)
                    .returns(VOID)
                .action("interchange")
                    .tooltip("Interchanges two for loops, if possible")
                    .param("otherLoop", jpRef("loop"))
                    .returns(VOID)
                .action("tile")
                    .tooltip("Applies loop tiling to this loop")
                    .param("blockSize", STRING)
                    .param("reference", jpRef("statement"))
                    .param("useTernary", BOOLEAN, "true")
                    .returns(jpRef("statement"))
                .action("setCondRelation")
                    .tooltip("Changes the operator of a canonical condition, if possible. Supported operators: lt, le, gt, ge")
                    .param("operator", enumRef("Relation"))
                    .returns(VOID)
                .action("setBody")
                    .tooltip("Sets the body of the loop")
                    .param("body", jpRef("scope"))
                    .returns(VOID);

        joinPoint("if").extending("statement")
                .attribute("cond", jpRef("expression"))
                .attribute("condDecl", jpRef("vardecl"))
                .attribute("then", jpRef("scope"))
                .attribute("else", jpRef("scope"))
                .action("setCond")
                    .tooltip("Sets the condition of the if")
                    .param("cond", jpRef("expression"))
                    .returns(VOID)
                .action("setThen")
                    .tooltip("Sets the body of the if")
                    .param("then", jpRef("statement"))
                    .returns(VOID)
                .action("setElse")
                    .tooltip("Sets the body of the else")
                    .param("else", jpRef("statement"))
                    .returns(VOID);

        joinPoint("wrapperStmt").extending("statement")
                .attribute("kind", enumRef("WrapperStatementKind"))
                .attribute("content", jpRef("joinpoint"));

        joinPoint("returnStmt").extending("statement")
                .attribute("returnExpr", jpRef("expression"));

        joinPoint("switch").extending("statement")
                .attribute("hasDefaultCase", BOOLEAN, "True if there is a default case in this switch statement, false otherwise")
                .attribute("getDefaultCase", jpRef("case"), "The default case statement of this switch statement or undefined if it does not have a default case")
                .attribute("cases", array(jpRef("case")), "The case statements inside this switch")
                .attribute("condition", jpRef("expression"));

        joinPoint("switchCase").extending("statement");

        joinPoint("case").extending("switchCase")
                .attribute("isDefault", BOOLEAN)
                .attribute("isEmpty", BOOLEAN, "True if this case does not contain instructions (i.e., it is directly above another case), false otherwise")
                .attribute("nextInstruction", jpRef("statement"), "The first statement that is not a case that will be executed by this case statement")
                .attribute("instructions", array(jpRef("statement")), "The instructions that are associated with this case in the source code. This does not represent what instructions are actually executed (e.g., if a case does not have a break, does not show instructions of the next case)")
                .attribute("nextCase", jpRef("case"), "The case statement that comes after this case, or undefined if there are no more case statements")
                .attribute("values", array(jpRef("expression")), "The values that the case statement will match. It can return zero (e.g., 'default:'), one (e.g., 'case 1:') or two (e.g., 'case 2...4:') expressions, depending on the format of the case");

        joinPoint("default").extending("switchCase");

        joinPoint("declStmt").extending("statement")
                .attribute("decls", array(jpRef("decl")), "The declarations in this statement");

        joinPoint("exprStmt").extending("statement")
                .attribute("expr", jpRef("expression"), "The expression join point associated to this exprStmt");

        joinPoint("gotoStmt").extending("statement")
                .attribute("label", jpRef("labelDecl"))
                .action("setLabel")
                    .tooltip("Sets the label of the goto")
                    .param("label", jpRef("labelDecl"))
                    .returns(VOID);

        joinPoint("labelStmt").extending("statement")
                .attribute("decl", jpRef("labelDecl"))
                .action("setDecl")
                    .tooltip("Sets the label of the label statement")
                    .param("label", jpRef("labelDecl"))
                    .returns(VOID);

        joinPoint("emptyStmt").extending("statement");

        joinPoint("continue").extending("statement");

        joinPoint("break").extending("statement")
                .attribute("enclosingStmt", jpRef("statement"), "The enclosing statement related to this break. It should be either a loop or a switch statement.");

        joinPoint("asmStmt").extending("statement")
                .attribute("isSimple", BOOLEAN)
                .attribute("isVolatile", BOOLEAN)
                .attribute("clobbers", array(STRING));

        // --- Expressions ---

        joinPoint("expression")
                .attribute("decl", jpRef("decl"), "A 'decl' join point that represents the declaration associated with this expression, or undefined if there is none")
                .attribute("vardecl", jpRef("vardecl"), "A 'vardecl' join point that represents the variable declaration associated with this expression, or undefined if there is none")
                .attribute("use", enumRef("ExpressionUse"))
                .attribute("isFunctionArgument", BOOLEAN, "True if the expression is part of an argument of a function call")
                .attribute("implicitCast", jpRef("cast"), "Returns a cast joinpoint if this expression has an associated implicit cast, undefined otherwise");

        joinPoint("call").extending("expression")
                .defaultAttribute("name")
                .attribute("name", STRING)
                .attribute("numArgs", INT)
                .attribute("memberNames", array(STRING))
                .attribute("declaration", jpRef("function"), "A 'function' join point that represents the function of the call that was found, it can return either an implementation or a function prototype; 'undefined' if no declaration was found")
                .attribute("definition", jpRef("function"), "A 'function' join point that represents the function definition of the call; 'undefined' if no definition was found")
                .attribute("argList", array(jpRef("expression")), "[DEPRECATED:] An alias for 'args'")
                .attribute("args", array(jpRef("expression")), "An array with the arguments of the call")
                .attribute("getArg")
                    .param("index", INT)
                    .returns(jpRef("expression"))
                .attribute("returnType", jpRef("type"), "The return type of the call")
                .attribute("functionType", jpRef("functionType"), "The function type of the call, which includes the return type and the types of the parameters")
                .attribute("isMemberAccess", BOOLEAN)
                .attribute("memberAccess", jpRef("memberAccess"))
                .attribute("isStmtCall", BOOLEAN)
                .attribute("function", jpRef("function"), "A function join point associated with this call. If a definition is present, it is given priority over returning a declaration. If only declarations are present, returns a declaration")
                .attribute("signature", STRING, "Similar to $function.signature, but if no function decl could be found (e.g., function from system include), returns a signature based on just the name of the function")
                .attribute("directCallee", jpRef("function"), "A function join point that represents the 'raw' function of the call (e.g. if this is a call to a templated function, returns a declaration representing the template specialization, instead of the original function)")
                .action("setName")
                    .tooltip("Changes the name of the call")
                    .param("name", STRING)
                    .returns(VOID)
                .action("wrap")
                    .tooltip("Wraps this call with a possibly new wrapping function")
                    .param("name", STRING)
                    .returns(VOID)
                .action("inline")
                    .tooltip("Tries to inline this call")
                    .returns(BOOLEAN)
                .action("setArgFromString")
                    .param("index", INT)
                    .param("expr", STRING)
                    .returns(VOID)
                .action("setArg")
                    .param("index", INT)
                    .param("expr", jpRef("expression"))
                    .returns(VOID)
                .action("addArg")
                    .tooltip("Adds an argument at the end of the call, creating an expression using the given code and type. If a type is not provided, a dummy type is used")
                    .param("argCode", STRING)
                    .param("type", jpRef("type"), "null")
                    .returns(VOID)
                .action("addArg")
                    .tooltip("Adds an argument at the end of the call, creating a literal 'type' from the type string")
                    .param("arg", STRING)
                    .param("type", STRING)
                    .returns(VOID);

        joinPoint("memberCall").extending("call")
                .attribute("base", jpRef("expression"))
                .attribute("rootBase", jpRef("expression"));

        joinPoint("cudaKernelCall").extending("call")
                .attribute("config", array(jpRef("expression")))
                .action("setConfig")
                    .param("args", array(jpRef("expression")))
                    .returns(VOID)
                .action("setConfigFromStrings")
                    .param("args", array(STRING))
                    .returns(VOID);

        joinPoint("op").extending("expression")
                .attribute("operator", STRING)
                .attribute("kind", enumRef("OpKind"), "The kind of the operator. If it is a binary operator, can be one of: ptr_mem_d, ptr_mem_i, mul, div, rem, add, sub, shl, shr, cmp, lt, gt, le, ge, eq, ne, and, xor, or, l_and, l_or, assign, mul_assign, div_assign, rem_assign, add_assign, sub_assign, shl_assign, shr_assign, and_assign, xor_assign, or_assign, comma. If it is a unary operator, can be one of: post_inc, post_dec, pre_inc, pre_dec, addr_of, deref, plus, minus, not, l_not, real, imag, extension, cowait. If it is a ternary operator, the value will be 'ternary'")
                .attribute("isBitwise", BOOLEAN);

        joinPoint("binaryOp").extending("op")
                .attribute("left", jpRef("expression"))
                .attribute("right", jpRef("expression"))
                .attribute("isAssignment", BOOLEAN)
                .action("setLeft")
                    .param("left", jpRef("expression"))
                    .returns(VOID)
                .action("setRight")
                    .param("right", jpRef("expression"))
                    .returns(VOID);

        joinPoint("unaryOp").extending("op")
                .attribute("operand", jpRef("expression"))
                .attribute("isPointerDeref", BOOLEAN);

        joinPoint("ternaryOp").extending("op")
                .attribute("cond", jpRef("expression"))
                .attribute("trueExpr", jpRef("expression"))
                .attribute("falseExpr", jpRef("expression"));

        joinPoint("newExpr").extending("expression");

        joinPoint("deleteExpr").extending("expression");

        joinPoint("varref").extending("expression")
                .tooltip("A reference to a variable")
                .defaultAttribute("name")
                .attribute("name", STRING)
                .attribute("kind", STRING)
                .attribute("useExpr", jpRef("expression"), "Expression from where the attribute 'use' is calculated. In certain cases (e.g., array access, pointer dereference) the 'use' attribute is not calculated on the node itself, but on an ancestor of the node. This attribute returns that node")
                .attribute("isFunctionCall", BOOLEAN, "True if this varref represents a function call")
                .attribute("declaration", jpRef("declarator"))
                .attribute("property", STRING, "If this variable reference has a MS-style property, returns the property name. Returns undefined otherwise")
                .attribute("hasProperty", BOOLEAN, "True if this variable reference has a MS-style property, false otherwise")
                .action("setName")
                    .param("name", STRING)
                    .returns(VOID);

        joinPoint("cast").extending("expression")
                .attribute("isImplicitCast", BOOLEAN, "[DEPRECATED: Use expr.implicitCast instead]")
                .attribute("fromType", jpRef("type"))
                .attribute("toType", jpRef("type"))
                .attribute("subExpr", jpRef("expression"));

        joinPoint("parenExpr").extending("expression")
                .attribute("subExpr", jpRef("expression"), "Returns the expression inside this parenthesis expression");

        joinPoint("arrayAccess").extending("expression")
                .attribute("arrayVar", jpRef("expression"), "Expression representing the variable of the array access (can be a varref, memberAccess...)")
                .attribute("subscript", array(jpRef("expression")), "Expression of the array access subscript")
                .attribute("parentAccess", jpRef("arrayAccess"), "A view of the current arrayAccess without the last subscript, or undefined if this arrayAccess only has one subscript")
                .attribute("numSubscripts", INT, "The number of subscripts of this array access")
                .attribute("name", STRING, "If the array access is done over a variable, returns the name of the variable. Equivalent to $arrayAccess.arrayVar.name");

        joinPoint("memberAccess").extending("expression")
                .attribute("name", STRING)
                .attribute("memberChain", array(jpRef("expression")))
                .attribute("memberChainNames", array(STRING))
                .attribute("base", jpRef("expression"), "Expression of the base of this member access")
                .attribute("arrow", BOOLEAN, "True if this is a member access that uses arrow (i.e., foo->bar), false if uses dot (i.e., foo.bar)")
                .action("setArrow")
                    .param("isArrow", BOOLEAN)
                    .returns(VOID);

        joinPoint("unaryExprOrType").extending("expression")
                .attribute("kind", STRING)
                .attribute("hasTypeExpr", BOOLEAN)
                .attribute("hasArgExpr", BOOLEAN)
                .attribute("argType", jpRef("type"))
                .attribute("argExpr", jpRef("expression"))
                .action("setArgType")
                    .param("argType", jpRef("type"))
                    .returns(VOID);

        joinPoint("This").extending("expression");

        joinPoint("literal").extending("expression");

        joinPoint("intLiteral").extending("literal")
                .attribute("value", LONG);

        joinPoint("floatLiteral").extending("literal")
                .attribute("value", DOUBLE);

        joinPoint("boolLiteral").extending("literal")
                .attribute("value", BOOLEAN);

        joinPoint("initList").extending("expression")
                .attribute("arrayFiller", jpRef("expression"), "[May be undefined] If this initializer list initializes an array with more elements than there are initializers in the list, specifies an expression to be used for value initialization of the rest of the elements");

        joinPoint("implicitValue").extending("expression");

        // --- Comment ---

        joinPoint("comment")
                .attribute("text", STRING)
                .action("setText")
                    .param("text", STRING)
                    .returns(VOID);

        // --- Cilk ---

        joinPoint("cilkFor").extending("loop");

        joinPoint("cilkSync").extending("statement");

        joinPoint("cilkSpawn").extending("call");

        // --- Attribute ---

        joinPoint("attribute")
                .attribute("kind", STRING);

        // --- Types ---

        joinPoint("type")
                .attribute("kind", STRING)
                .attribute("isTopLevel", BOOLEAN)
                .attribute("isArray", BOOLEAN)
                .attribute("isPointer", BOOLEAN)
                .attribute("isAuto", BOOLEAN, "True if this is a type declared with the 'auto' keyword")
                .attribute("arraySize", INT)
                .attribute("arrayDims", array(INT))
                .attribute("hasTemplateArgs", BOOLEAN)
                .attribute("templateArgsStrings", array(STRING))
                .attribute("templateArgsTypes", array(jpRef("type")))
                .attribute("hasSugar", BOOLEAN)
                .attribute("desugar", jpRef("type"), "Single-step desugar. Returns the type itself if it does not have sugar")
                .attribute("desugarAll", jpRef("type"), "Completely desugars the type")
                .attribute("isBuiltin", BOOLEAN)
                .attribute("constant", BOOLEAN)
                .attribute("unwrap", jpRef("type"), "If the type encapsulates another type, returns the encapsulated type")
                .attribute("normalize", jpRef("type"), "Ignores certain types (e.g., DecayedType)")
                .attribute("typeFields", map(STRING, jpRef("type")), "Maps names of join point fields that represent type join points, to their respective values")
                .attribute("fieldTree", STRING, "A tree representation of the fields of this type")
                .action("setTemplateArgsTypes")
                    .tooltip("Sets the template argument types of a template type")
                    .param("templateArgTypes", array(jpRef("type")))
                    .returns(VOID)
                .action("setTemplateArgType")
                    .tooltip("Sets a single template argument type of a template type")
                    .param("index", INT)
                    .param("templateArgType", jpRef("type"))
                    .returns(VOID)
                .action("setDesugar")
                    .tooltip("Sets the desugared type of this type")
                    .param("desugaredType", jpRef("type"))
                    .returns(VOID)
                .action("setTypeFieldByValueRecursive")
                    .tooltip("Changes a single occurrence of a type field that has the current value with new value. Returns true if there was a change")
                    .param("currentValue", OBJECT)
                    .param("newValue", OBJECT)
                    .returns(BOOLEAN)
                .action("setUnderlyingType")
                    .tooltip("Replaces an underlying type of this instance with new type, if it matches the old type")
                    .param("oldValue", jpRef("type"))
                    .param("newValue", jpRef("type"))
                    .returns(jpRef("type"))
                .action("asConst")
                    .tooltip("Returns a new node based on this type with the qualifier const")
                    .returns(jpRef("type"));

        joinPoint("pointerType").extending("type")
                .attribute("pointee", jpRef("type"))
                .attribute("pointerLevels", INT, "Number of pointer levels from this pointer")
                .action("setPointee")
                    .tooltip("Sets the pointee type of this pointer type")
                    .param("pointeeType", jpRef("type"))
                    .returns(VOID);

        joinPoint("arrayType").extending("type")
                .attribute("elementType", jpRef("type"))
                .action("setElementType")
                    .tooltip("Sets the element type of the array")
                    .param("arrayElementType", jpRef("type"))
                    .returns(VOID);

        joinPoint("adjustedType").extending("type")
                .attribute("originalType", jpRef("type"), "The type that is being adjusted");

        joinPoint("variableArrayType").extending("arrayType")
                .attribute("sizeExpr", jpRef("expression"))
                .action("setSizeExpr")
                    .tooltip("Sets the size expression of this variable array type")
                    .param("sizeExpr", jpRef("expression"))
                    .returns(VOID);

        joinPoint("incompleteArrayType").extending("arrayType");

        joinPoint("tagType").extending("type")
                .attribute("name", STRING)
                .attribute("decl", jpRef("decl"), "A 'decl' join point that represents the declaration of this tag type");

        joinPoint("enumType").extending("tagType")
                .attribute("integerType", jpRef("type"));

        joinPoint("templateSpecializationType").extending("type")
                .attribute("templateName", STRING)
                .attribute("numArgs", INT)
                .attribute("args", array(STRING))
                .attribute("firstArgType", jpRef("type"));

        joinPoint("functionType").extending("type")
                .attribute("returnType", jpRef("type"))
                .attribute("paramTypes", array(jpRef("type")))
                .action("setReturnType")
                    .tooltip("Sets the return type of the FunctionType")
                    .param("newType", jpRef("type"))
                    .returns(VOID)
                .action("setParamType")
                    .tooltip("Sets the type of a parameter of the FunctionType. Be careful that if you directly change the type of a parameter and the function type is associated with a function declaration, this change will not be reflected in the function. If you want to change the type of a parameter of a function declaration, use function.setParamType")
                    .param("index", INT)
                    .param("newType", jpRef("type"))
                    .returns(VOID);

        joinPoint("qualType").extending("type")
                .attribute("qualifiers", array(STRING))
                .attribute("unqualifiedType", jpRef("type"));

        joinPoint("builtinType").extending("type")
                .attribute("builtinKind", STRING)
                .attribute("isInteger", BOOLEAN, "True, if it is an integer type")
                .attribute("isFloat", BOOLEAN, "True, if it is a floating type (e.g., float, double)")
                .attribute("isSigned", BOOLEAN, "True, if it is a signed type")
                .attribute("isUnsigned", BOOLEAN, "True, if it is an unsigned type")
                .attribute("isVoid", BOOLEAN, "True, if it is a void type");

        joinPoint("parenType").extending("type")
                .attribute("innerType", jpRef("type"))
                .action("setInnerType")
                    .tooltip("Sets the inner type of this paren type")
                    .param("innerType", jpRef("type"))
                    .returns(VOID);

        joinPoint("undefinedType").extending("type");

        joinPoint("elaboratedType").extending("type")
                .tooltip(
                        "Represents a type that was referred to using an elaborated type keyword, e.g., struct S, or via a qualified name, e.g., N::M::type, or both. This type is used to keep track of a type name as written in the source code, including tag keywords and any nested-name-specifiers. The type itself is always 'sugar', used to express what was written in the source code but containing no additional semantic information.")
                .attribute("keyword", STRING, "The keyword of this elaborated type, if present. Can be one of: struct, interface, union, class, enum, typename")
                .attribute("qualifier", STRING,"The qualifier of this elaborated type, if present (e.g., A::)")
                .attribute("namedType", jpRef("type"), "The type that is being prefixed with the qualifier");

        joinPoint("typedefType").extending("type")
                .attribute("decl", jpRef("typedefNameDecl"), "The typedef declaration associated with this typedef type")
                .attribute("underlyingType", jpRef("type"), "The type being aliased");
    }
}
