/**
 * Copyright 2018 SPeCS.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License. under the License.
 */

package pt.up.fe.specs.clava.ast.attr.enums;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import pt.up.fe.specs.util.SpecsStrings;
import pt.up.fe.specs.util.enums.EnumHelperWithValue;
import pt.up.fe.specs.util.lazy.Lazy;
import pt.up.fe.specs.util.providers.StringProvider;
import pt.up.fe.specs.util.utilities.CachedItems;

public enum AttributeKind implements StringProvider {

    AddressSpace,
    AnnotateType,
    ArmMveStrictPolymorphism,
    BTFTypeTag,
    CmseNSCall,
    NoDeref,
    ObjCGC,
    ObjCInertUnsafeUnretained,
    ObjCKindOf,
    OpenCLConstantAddressSpace,
    OpenCLGenericAddressSpace,
    OpenCLGlobalAddressSpace,
    OpenCLGlobalDeviceAddressSpace,
    OpenCLGlobalHostAddressSpace,
    OpenCLLocalAddressSpace,
    OpenCLPrivateAddressSpace,
    Ptr32,
    Ptr64,
    SPtr,
    TypeNonNull,
    TypeNullUnspecified,
    TypeNullable,
    TypeNullableResult,
    UPtr,
    FallThrough,
    Likely,
    MustTail,
    OpenCLUnrollHint,
    Suppress,
    Unlikely,
    AlwaysInline,
    NoInline,
    NoMerge,
    AArch64SVEPcs,
    AArch64VectorPcs,
    AMDGPUKernelCall,
    AcquireHandle,
    AnyX86NoCfCheck,
    CDecl,
    FastCall,
    IntelOclBicc,
    LifetimeBound,
    MSABI,
    NSReturnsRetained,
    ObjCOwnership,
    Pascal,
    Pcs,
    PreserveAll,
    PreserveMost,
    RegCall,
    StdCall,
    SwiftAsyncCall,
    SwiftCall,
    SysVABI,
    ThisCall,
    VectorCall,
    SwiftAsyncContext,
    SwiftContext,
    SwiftErrorResult,
    SwiftIndirectResult,
    Annotate,
    CFConsumed,
    CarriesDependency,
    NSConsumed,
    NonNull,
    OSConsumed,
    PassObjectSize,
    ReleaseHandle,
    UseHandle,
    AMDGPUFlatWorkGroupSize,
    AMDGPUNumSGPR,
    AMDGPUNumVGPR,
    AMDGPUWavesPerEU,
    ARMInterrupt,
    AVRInterrupt,
    AVRSignal,
    AcquireCapability,
    AcquiredAfter,
    AcquiredBefore,
    AlignMac68k,
    AlignNatural,
    Aligned,
    AllocAlign,
    AllocSize,
    AlwaysDestroy,
    AnalyzerNoReturn,
    AnyX86Interrupt,
    AnyX86NoCallerSavedRegisters,
    ArcWeakrefUnavailable,
    ArgumentWithTypeTag,
    ArmBuiltinAlias,
    Artificial,
    AsmLabel,
    AssertCapability,
    AssertExclusiveLock,
    AssertSharedLock,
    AssumeAligned,
    Assumption,
    Availability,
    BPFPreserveAccessIndex,
    BTFDeclTag,
    Blocks,
    Builtin,
    C11NoReturn,
    CFAuditedTransfer,
    CFGuard,
    CFICanonicalJumpTable,
    CFReturnsNotRetained,
    CFReturnsRetained,
    CFUnknownTransfer,
    CPUDispatch,
    CPUSpecific,
    CUDAConstant,
    CUDADevice,
    CUDADeviceBuiltinSurfaceType,
    CUDADeviceBuiltinTextureType,
    CUDAGlobal,
    CUDAHost,
    CUDAInvalidTarget,
    CUDALaunchBounds,
    CUDAShared,
    CXX11NoReturn,
    CallableWhen,
    Callback,
    Capability,
    CapturedRecord,
    Cleanup,
    CmseNSEntry,
    CodeSeg,
    Cold,
    Common,
    Const,
    ConstInit,
    Constructor,
    Consumable,
    ConsumableAutoCast,
    ConsumableSetOnRead,
    Convergent,
    DLLExport,
    DLLExportStaticLocal,
    DLLImport,
    DLLImportStaticLocal,
    Deprecated,
    Destructor,
    DiagnoseAsBuiltin,
    DiagnoseIf,
    DisableSanitizerInstrumentation,
    DisableTailCalls,
    EmptyBases,
    EnableIf,
    EnforceTCB,
    EnforceTCBLeaf,
    EnumExtensibility,
    Error,
    ExcludeFromExplicitInstantiation,
    ExclusiveTrylockFunction,
    ExternalSourceSymbol,
    Final,
    FlagEnum,
    Flatten,
    Format,
    FormatArg,
    FunctionReturnThunks,
    GNUInline,
    GuardedBy,
    GuardedVar,
    HIPManaged,
    HLSLNumThreads,
    HLSLSV_GroupIndex,
    HLSLShader,
    Hot,
    IBAction,
    IBOutlet,
    IBOutletCollection,
    InitPriority,
    InternalLinkage,
    LTOVisibilityPublic,
    LayoutVersion,
    Leaf,
    LockReturned,
    LocksExcluded,
    M68kInterrupt,
    MIGServerRoutine,
    MSAllocator,
    MSInheritance,
    MSNoVTable,
    MSP430Interrupt,
    MSStruct,
    MSVtorDisp,
    MaxFieldAlignment,
    MayAlias,
    MicroMips,
    MinSize,
    MinVectorWidth,
    Mips16,
    MipsInterrupt,
    MipsLongCall,
    MipsShortCall,
    NSConsumesSelf,
    NSErrorDomain,
    NSReturnsAutoreleased,
    NSReturnsNotRetained,
    Naked,
    NoAlias,
    NoCommon,
    NoDebug,
    NoDestroy,
    NoDuplicate,
    NoInstrumentFunction,
    NoMicroMips,
    NoMips16,
    NoProfileFunction,
    NoRandomizeLayout,
    NoReturn,
    NoSanitize,
    NoSpeculativeLoadHardening,
    NoSplitStack,
    NoStackProtector,
    NoThreadSafetyAnalysis,
    NoThrow,
    NoUniqueAddress,
    NotTailCalled,
    OMPAllocateDecl,
    OMPCaptureNoInit,
    OMPDeclareTargetDecl,
    OMPDeclareVariant,
    OMPThreadPrivateDecl,
    OSConsumesThis,
    OSReturnsNotRetained,
    OSReturnsRetained,
    OSReturnsRetainedOnNonZero,
    OSReturnsRetainedOnZero,
    ObjCBridge,
    ObjCBridgeMutable,
    ObjCBridgeRelated,
    ObjCException,
    ObjCExplicitProtocolImpl,
    ObjCExternallyRetained,
    ObjCIndependentClass,
    ObjCMethodFamily,
    ObjCNSObject,
    ObjCPreciseLifetime,
    ObjCRequiresPropertyDefs,
    ObjCRequiresSuper,
    ObjCReturnsInnerPointer,
    ObjCRootClass,
    ObjCSubclassingRestricted,
    OpenCLIntelReqdSubGroupSize,
    OpenCLKernel,
    OptimizeNone,
    Override,
    Owner,
    Ownership,
    Packed,
    ParamTypestate,
    PatchableFunctionEntry,
    Pointer,
    PragmaClangBSSSection,
    PragmaClangDataSection,
    PragmaClangRelroSection,
    PragmaClangRodataSection,
    PragmaClangTextSection,
    PreferredName,
    PtGuardedBy,
    PtGuardedVar,
    Pure,
    RISCVInterrupt,
    RandomizeLayout,
    Reinitializes,
    ReleaseCapability,
    ReqdWorkGroupSize,
    RequiresCapability,
    Restrict,
    Retain,
    ReturnTypestate,
    ReturnsNonNull,
    ReturnsTwice,
    SYCLKernel,
    SYCLSpecialClass,
    ScopedLockable,
    Section,
    SelectAny,
    Sentinel,
    SetTypestate,
    SharedTrylockFunction,
    SpeculativeLoadHardening,
    StandaloneDebug,
    StrictFP,
    SwiftAsync,
    SwiftAsyncError,
    SwiftAsyncName,
    SwiftAttr,
    SwiftBridge,
    SwiftBridgedTypedef,
    SwiftError,
    SwiftName,
    SwiftNewType,
    SwiftPrivate,
    TLSModel,
    Target,
    TargetClones,
    TestTypestate,
    TransparentUnion,
    TrivialABI,
    TryAcquireCapability,
    TypeTagForDatatype,
    TypeVisibility,
    Unavailable,
    Uninitialized,
    Unused,
    Used,
    UsingIfExists,
    Uuid,
    VecReturn,
    VecTypeHint,
    Visibility,
    WarnUnused,
    WarnUnusedResult,
    Weak,
    WeakImport,
    WeakRef,
    WebAssemblyExportName,
    WebAssemblyImportModule,
    WebAssemblyImportName,
    WorkGroupSizeHint,
    X86ForceAlignArgPointer,
    XRayInstrument,
    XRayLogArgs,
    ZeroCallUsedRegs,
    AbiTag,
    Alias,
    AlignValue,
    BuiltinAlias,
    CalledOnce,
    IFunc,
    InitSeg,
    LoaderUninitialized,
    LoopHint,
    Mode,
    NoBuiltin,
    NoEscape,
    OMPCaptureKind,
    OMPDeclareSimdDecl,
    OMPReferencedVar,
    ObjCBoxable,
    ObjCClassStub,
    ObjCDesignatedInitializer,
    ObjCDirect,
    ObjCDirectMembers,
    ObjCNonLazyClass,
    ObjCNonRuntimeProtocol,
    ObjCRuntimeName,
    ObjCRuntimeVisible,
    OpenCLAccess,
    Overloadable,
    RenderScriptKernel,
    SwiftObjCMembers,
    Thread,
    FirstAttr,
    LastAttr,
    FirstTypeAttr,
    LastTypeAttr,
    FirstStmtAttr,
    LastStmtAttr,
    FirstDeclOrStmtAttr,
    LastDeclOrStmtAttr,
    FirstInheritableAttr,
    LastInheritableAttr,
    FirstDeclOrTypeAttr,
    LastDeclOrTypeAttr,
    FirstInheritableParamAttr,
    LastInheritableParamAttr,
    FirstParameterABIAttr,
    LastParameterABIAttr;

    private static final Lazy<EnumHelperWithValue<AttributeKind>> ENUM_HELPER = EnumHelperWithValue
            .newLazyHelperWithValue(AttributeKind.class);

    public static EnumHelperWithValue<AttributeKind> getHelper() {
        return ENUM_HELPER.get();
    }

    private static final Set<AttributeKind> IS_INLINE = new HashSet<>(
            Arrays.asList(OpenCLKernel, CUDAGlobal, CUDAConstant, CUDAShared));
    private static final Set<AttributeKind> IS_LOWERCASE = new HashSet<>(Arrays.asList(NonNull));

    private static final CachedItems<AttributeKind, String> ATTRIBUTE_NAMES = new CachedItems<>(
            AttributeKind::toAttributeName);

    @Override
    public String getString() {
        return name();
    }

    public String getAttributeName() {
        return ATTRIBUTE_NAMES.get(this);
    }

    private static String toAttributeName(AttributeKind kind) {
        String name = kind.name();

        // Make certain expressions lower-case
        if (name.contains("OpenCL")) {
            name = name.replace("OpenCL", "Opencl");
        }
        if (IS_LOWERCASE.contains(kind)) {
            return name.toLowerCase();
        }

        // Special case: TypeVisibility attribute is "visibility"
        if (kind == TypeVisibility) {
            name = Visibility.name();
        }

        return SpecsStrings.camelCaseSeparate(name, "_").toLowerCase();
    }

    /**
     * 
     * @return true if this attribute kind should be written inlined in the code (e.g., kernel)
     */
    public boolean isInline() {
        return IS_INLINE.contains(this);
    }

}
