cmake_minimum_required(VERSION 3.5)

# Applies a LARA file to the given target.
#
# Sources and includes of the target will be updated in order to point to the code generated by Clava.
#
# Parameter 1: The target that the LARA file will be applied to
# Parameter 2: A LARA file
# Parameter ARGS (one value): A string with the aspect arguments e.g., "inputFile:'data.json', execute:true, iterations:10"
# Parameter FLAGS (multi-value): A list of flags that will be passed to Clava during execution
function(clava_weave ORIG_TARGET ASPECT)

    set(options)
    set(oneValueArgs ARGS)
    set(multiValueArgs FLAGS)

    cmake_parse_arguments(PARSE_ARGV 2 CLAVA_WEAVE "${options}" "${oneValueArgs}" "${multiValueArgs}")

	#message(STATUS "ASPECT_ARGS: " ${CLAVA_WEAVE_ASPECT_ARGS})
	#message(STATUS "WEAVER_ARGS: " ${CLAVA_WEAVE_WEAVER_ARGS})

	# Create aspect arguments
	if(NOT ("${CLAVA_WEAVE_ARGS}" STREQUAL ""))
		set(ASPECT_ARGS_FLAG "-av")
		set(ASPECT_ARGS "{${CLAVA_WEAVE_ARGS}}")	
	else()
		set(ASPECT_ARGS_FLAG "")
		set(ASPECT_ARGS "")	
	endif()
	
	# Get build dir
	set(BUILD_DIR "${CMAKE_CURRENT_BINARY_DIR}")
	#message(STATUS "BUILD DIR: ${BUILD_DIR}") 

	# Woven dir name
	set(WOVEN_DIR_NAME "woven")
	
	# Working dir
	set(WORKING_DIR "${BUILD_DIR}/${ORIG_TARGET}_clava_weave")
	# Woven dir
	set(WOVEN_DIR "${WORKING_DIR}/${WOVEN_DIR_NAME}")

	file(MAKE_DIRECTORY ${WOVEN_DIR})
	#message(STATUS "Woven dir: ${WOVEN_DIR}")
	

	# Get CMakeLists.txt dir
	get_target_property(ORIG_CMAKE_DIR ${ORIG_TARGET} SOURCE_DIR)
	#message(STATUS "ORIG_CMAKE_DIR: ${ORIG_CMAKE_DIR}")


	
	# Set absolute path of aspect file relative to the source folder, in case path is relative
	if(NOT IS_ABSOLUTE ${ASPECT})
		set(ASPECT "${ORIG_CMAKE_DIR}/${ASPECT}")	
	endif()
	#message(STATUS "ASPECT: ${ASPECT}")

	
	# Get original source files
	get_target_property(ORIG_SOURCES ${ORIG_TARGET} SOURCES)
	#message(STATUS "ORIG_SOURCES: ${ORIG_SOURCES}")
	
	# Initialize processed sources
	set(PROC_ORIG_SOURCES "")
	foreach(SOURCE ${ORIG_SOURCES})
		if(IS_ABSOLUTE ${SOURCE})
			set(PROC_SOURCE "${SOURCE}")	
		else()
			set(PROC_SOURCE "${ORIG_CMAKE_DIR}/${SOURCE}")			
		endif()
		
		LIST(APPEND PROC_ORIG_SOURCES "${PROC_SOURCE}")
	endforeach()	
	#message(STATUS "NEW PROC_ORIG_SOURCES: ${PROC_ORIG_SOURCES}")

	# Process original source file list
	if(NOT "${CMAKE_HOST_SYSTEM}" MATCHES ".*Windows.*")
		string(REGEX REPLACE ";" ":" PROC_ORIG_SOURCES "${PROC_ORIG_SOURCES}")
	endif()
	#message(STATUS "PROC_ORIG_SOURCES: ${PROC_ORIG_SOURCES}")
	
	
	# Get original include folders
	get_target_property(ORIG_INCLUDES ${ORIG_TARGET} INCLUDE_DIRECTORIES)
	#message(STATUS "ORIG_INCLUDES: '${ORIG_INCLUDES}'")

	set(INCLUDE_HEADERS_FLAG "-ih")
    if((${ORIG_INCLUDES} MATCHES "ORIG_INCLUDES-NOTFOUND") OR ("${ORIG_INCLUDES}" STREQUAL ""))
        set(INCLUDE_HEADERS_FLAG "")
        set(ORIG_INCLUDES "")
    endif()
	#message(STATUS "ORIG_INCLUDES AFTER: '${ORIG_INCLUDES}'")

	
	# Process original includes list
	string(REGEX REPLACE "([^;]+)" "\\1" PROC_ORIG_INCLUDES "${ORIG_INCLUDES}")
	#message(STATUS "PROC_ORIG_INCLUDES: '${ORIG_INCLUDES}'")

	if(NOT "${CMAKE_HOST_SYSTEM}" MATCHES ".*Windows.*")
		string(REGEX REPLACE ";" ":" PROC_ORIG_INCLUDES "${PROC_ORIG_INCLUDES}")
	endif()
	#message(STATUS "INCLUDE HEADERS FLAG: ${INCLUDE_HEADERS_FLAG}")
	#message(STATUS "PROC_ORIG_INCLUDES AFTER REPLACE: ${PROC_ORIG_INCLUDES}")
	
	
	# Make the CMake configuration dependent on the LARA file and original sources
	set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ASPECT};${ORIG_SOURCES}")
	
	# Mark Clava output directory as a target for 'make clean'
	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_MAKE_CLEAN_FILES "${WOVEN_DIR}")
		
	
	
	# Clean file with woven sources, if present
	file(REMOVE "${WOVEN_DIR}/clava_generated_files.txt")
	
	# Create CMakeLists.txt for weaving
	configure_file("${Clava_DIR}/clava/ClavaWeave.CMakeLists.txt" "${WORKING_DIR}/CMakeLists.txt")
	
	message(STATUS "Configuring weaving step")
	execute_process(COMMAND ${CMAKE_COMMAND} -G "${CMAKE_GENERATOR}"
                        "${WORKING_DIR}"
               WORKING_DIRECTORY "${WORKING_DIR}")
			   
	message(STATUS "Executing weaving step")
	execute_process(COMMAND ${CMAKE_COMMAND} --build . --target "${ORIG_TARGET}_weaving"
                WORKING_DIRECTORY "${WORKING_DIR}")
			   
	# Read new sources
	if(EXISTS "${WOVEN_DIR}/clava_generated_files.txt")
        file(READ "${WOVEN_DIR}/clava_generated_files.txt" CLAVA_WOVEN_SOURCES)
        string(STRIP "${CLAVA_WOVEN_SOURCES}" CLAVA_WOVEN_SOURCES)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CLAVA_WOVEN_SOURCES}")

		# Set new sources
		set_target_properties(${ORIG_TARGET}
			PROPERTIES SOURCES "${CLAVA_WOVEN_SOURCES}"
		)		
		
        #message(STATUS "CLAVA_WOVEN_SOURCES: ${CLAVA_WOVEN_SOURCES}")
	else()
		message(FATAL_ERROR "Could not find Clava file 'clava_generated_files.txt'")
	endif()
	
	# Read new includes
	if(EXISTS "${WOVEN_DIR}/clava_include_dirs.txt")
        file(READ "${WOVEN_DIR}/clava_include_dirs.txt" CLAVA_INCLUDE_DIRS)
        string(STRIP "${CLAVA_INCLUDE_DIRS}" CLAVA_INCLUDE_DIRS)

		# Set new include directories
		set_target_properties(${ORIG_TARGET}
			PROPERTIES INCLUDE_DIRECTORIES "${CLAVA_INCLUDE_DIRS}"
		)			
		
        #message(STATUS "CLAVA_INCLUDE_DIRS: ${CLAVA_INCLUDE_DIRS}")
	else()
		message(FATAL_ERROR "Could not find Clava file 'clava_include_dirs.txt'")
	endif()
	
endfunction(clava_weave)
