# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI - Clava JS

on:
  push:
    branches: [ feature/clava-js ]
  pull_request:
    branches: [ feature/clava-js ]

  # Daily at midnight
  schedule:
    - cron: '0 0 * * *'

permissions:
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    #defaults:
    #  run:
    #    working-directory: ./..

    steps:
    - uses: actions/checkout@v4
      # Because of scheduled runs, by default run on default branch
      with:
        ref: feature/clava-js

    - name: Cache ivy dependencies
      id: cache-nivy
      uses: actions/cache@v3
      env:
          cache-name: cache-ivy-dependencies
      with:
          # ivy dependencies cache files are stored in `~/.ivy2` on Linux/macOS
          path: ~/.ivy2
          key: ${{ runner.os }}-build-${{ env.cache-name }}        
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate build.xml
      run: | 
        wget -q -N http://specs.fe.up.pt/tools/eclipse-build.jar
        java -jar eclipse-build.jar https://github.com/specs-feup/specs-java-libs https://github.com/specs-feup/lara-framework?commit=feature/lara-js ./
        wget -N -O /usr/share/ant/lib/ivy-2.5.0.jar specs.fe.up.pt/libs/ivy-2.5.0.jar
    - name: Build with Ant
      run: |
        ant -noinput -buildfile build.xml

    - name: List directory
      run: |
        echo "Current folder"
        ls
    - name: Publish Test Report 
      uses: mikepenz/action-junit-report@v3.6.1
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/reports-eclipse-build/TEST-*.xml'
        summary: true
        #exclude_sources: ''        
